"""Render docs/SOURCES.md from the seed (I-9), and check the committed copy matches.

    python -m research_gateway.registry.docs            # write gateway/docs/SOURCES.md
    python -m research_gateway.registry.docs --check    # exit 1 if the committed file is stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .load import read_seed, validate

DOCS = Path(__file__).resolve().parents[2] / "docs" / "SOURCES.md"

KIND_TITLES = {
    "article": "Article indexes",
    "dataset": "Dataset and repository indexes",
    "citation": "Citation graph",
    "resolver": "Resolvers and enrichment",
    "statistical": "Statistical data APIs",
    "manual": "Manual-only sources (documented, never queried by the gateway)",
}
VERDICT_TEXT = {
    "allow": "**allow** — the source's terms permit commercial use of what the gateway retrieves",
    "per-item": "**per-item** — the platform permits it, but each record carries its own licence; records without an allow-listed licence are dropped in commercial mode",
    "deny": "**deny** — the source's terms forbid commercial use (or require a paid tier)",
    "unknown": "**unknown** — no reuse terms could be located; fails closed for commercial-flagged requests",
}


def _rate_text(rate: dict) -> str:
    parts = []
    for key, unit in (("per_second", "/s"), ("per_minute", "/min"), ("per_hour", "/h"), ("per_day", "/day")):
        if rate.get(key):
            parts.append(f"{rate[key]:g}{unit}")
    if rate.get("cost_cap_per_day"):
        parts.append(f"cost cap {rate['cost_cap_per_day']}/day")
    if rate.get("burst"):
        parts.append(f"burst {rate['burst']}")
    text = ", ".join(parts) or "no live calls"
    flag = "verified" if rate.get("verified") else "**unverified — conservative default until confirmed**"
    return f"{text} ({flag})"


def render(sources: list[dict]) -> str:
    out = [
        "# Sources",
        "",
        "Every source the research gateway knows, generated from "
        "`research_gateway/registry/seed/sources.toml`. Do not edit this file by hand; "
        "edit the seed and run `python -m research_gateway.registry.docs`.",
        "",
        "**Personal, non-commercial research use is the baseline for every source listed here** — "
        "each was adopted only after its terms were read. The *Commercial* line is the one flag the "
        "gateway routes on; a request flagged commercial never touches a source whose verdict is "
        "`deny` or `unknown`, and drops individual records without an allow-listed licence from "
        "`per-item` sources. Unknowns are stated as unknown rather than guessed.",
        "",
        "Rate limits marked *unverified* are conservative defaults; the source stays disabled "
        "until the limit is confirmed from documentation or response headers.",
        "",
        "Keys are never stored in this repository. Each deployment maps the *secret name* below "
        "to an environment variable (`RESEARCH_GATEWAY_SECRET_<NAME>`) or a secrets backend.",
        "",
        "## Contents",
        "",
    ]
    by_kind: dict[str, list[dict]] = {}
    for s in sources:
        by_kind.setdefault(s["kind"], []).append(s)
    for kind in KIND_TITLES:
        if kind in by_kind:
            out.append(f"- {KIND_TITLES[kind]}: " + ", ".join(s["name"] for s in sorted(by_kind[kind], key=lambda x: x["name"])))
    out.append("")

    for kind in KIND_TITLES:
        if kind not in by_kind:
            continue
        out.append(f"## {KIND_TITLES[kind]}")
        out.append("")
        for s in sorted(by_kind[kind], key=lambda x: x["name"]):
            out.append(f"### {s['name']}")
            out.append("")
            out.append(f"- **Website:** {s['homepage']}")
            if s.get("docs_url"):
                out.append(f"- **API documentation:** {s['docs_url']}")
            caps = ", ".join(s.get("capabilities", [])) or "none (manual)"
            out.append(f"- **Gateway requests:** {caps}")
            if s.get("base_for"):
                out.append(f"- **Base lane for:** {', '.join(s['base_for'])}")
            if s.get("domains"):
                out.append(f"- **Added for domains:** {', '.join(s['domains'])}")
            out.append(f"- **Authentication:** {s['auth']}" + (f" (secret name `{s['secret_ref']}`)" if s.get("secret_ref") else ""))
            out.append(f"- **How to get access:** {s.get('key_instructions', '')}")
            out.append(f"- **Rate limit:** {_rate_text(s['rate'])} — {s['rate'].get('evidence', '')}")
            out.append(f"- **Licence:** {s.get('license', '')}")
            out.append(f"- **Commercial:** {VERDICT_TEXT[s['use_commercial']]}. Evidence: {s.get('use_evidence', '')}")
            if s.get("freshness_lag"):
                out.append(f"- **Freshness:** {s['freshness_lag']}")
            out.append(f"- **Enabled in the default seed:** {'yes' if s.get('enabled') else 'no'}")
            if s.get("notes"):
                out.append(f"- **Notes:** {s['notes']}")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="compare the committed file to the generated text")
    ap.add_argument("--out", default=str(DOCS))
    args = ap.parse_args(argv)
    sources = read_seed()
    problems = validate(sources)
    if problems:
        print("seed invalid; fix it before generating docs:", *problems, sep="\n  ", file=sys.stderr)
        return 2
    text = render(sources)
    if args.check:
        current = Path(args.out).read_text() if Path(args.out).exists() else ""
        if current != text:
            print(f"{args.out} is stale; regenerate with: python -m research_gateway.registry.docs", file=sys.stderr)
            return 1
        print("docs match the seed")
        return 0
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(text)
    print(f"wrote {args.out} ({len(sources)} sources)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
