"""Black-box tests for the size rules `tools/gen2_linecount.py --check` enforces
in `make gen2-check` (task 2r; charter "Size rules", the operator's ruling of
2026-09-29; INVARIANTS B-3).

Each test writes a throwaway git repository of literal files here (tracked
with `git add`, which is what the tool counts), runs the tool on it with
--check as a subprocess, and asserts the exit code and what it names.
Oracle: the rules as the charter states them, and line counts built here —
no hand-written file in the gen-2 surface (gen2/, gateway/, tools/gen2*,
tools/check_*, tools/gen_*, deploy/, Makefile, .github/) over 1,500 physical lines, exactly
1,500 passing; a generated file exempt only through the tool's GENERATED
list, each entry naming a tracked tool that names the file; and reaching
15,000 production lines stops the build for a growth review, where the gateway
service's production is its own budget (task 2b's split) and never counts toward it.
"""
from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TOOL = REPO / "tools" / "gen2_linecount.py"  # module global: tools/gen2_mutations.py points this at mutated copies

# One hand-written file at each place the per-file limit covers.
SURFACE = ("gen2/store/schema/05-big.sql", "gen2/tests/test_big.py", "tools/gen2_big.py", "tools/check_big.py", "tools/gen_big.py",
           "deploy/gen2/big.yaml", "Makefile", ".github/workflows/big.yml",
           "gateway/research_gateway/big.py", "gateway/tests/test_big.py")   # the gateway since task 2b-repair (A8)
# The two allowlisted files, and a stub of each tool naming the path it writes.
GENERATED = {"tools/gen2_mutation_controls.json": "tools/gen2_mutation_controls.py", "deploy/gen2.env.example": "tools/gen_source_catalog.py"}


def lines(n: int, text: str = "x = 1") -> str:
    return "".join(f"{text}  # {i}\n" for i in range(n))


class SizeRuleTest(unittest.TestCase):
    def check(self, files: dict[str, str], generated: bool = True, untracked: tuple[str, ...] = ()) -> subprocess.CompletedProcess:
        """The tool's --check on a repository of these files (with, unless
        generated=False, the allowlisted files and their tools, small), each
        tracked except those named in untracked, which are on disk only."""
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            tree = ({rel: "{}\n" for rel in GENERATED} | {tool: f'OUT = "{rel}"\n' for rel, tool in GENERATED.items()}) if generated else {}
            for rel, text in (tree | files).items():
                (root / rel).parent.mkdir(parents=True, exist_ok=True)
                (root / rel).write_text(text, encoding="utf-8")
            subprocess.run(["git", "init", "-q", str(root)], check=True, capture_output=True, timeout=60)
            subprocess.run(["git", "-C", str(root), "add", "-A"], check=True, capture_output=True, timeout=60)
            if untracked:
                subprocess.run(["git", "-C", str(root), "rm", "-q", "--cached", "--", *untracked], check=True, capture_output=True, timeout=60)
            return subprocess.run([sys.executable, str(TOOL), "--root", str(root), "--check"], capture_output=True, text=True, timeout=60)

    def test_a_hand_written_file_over_the_limit_fails_named_with_its_count(self) -> None:
        result = self.check({rel: lines(1501 + i) for i, rel in enumerate(SURFACE)})
        self.assertEqual(result.returncode, 1, msg=result.stderr)
        for i, rel in enumerate(SURFACE):
            with self.subTest(rel=rel):
                self.assertIn(f"FILE SIZE LIMIT EXCEEDED: {rel} has {1501 + i:,} lines > 1,500", result.stderr)

    def test_exactly_the_limit_passes(self) -> None:
        result = self.check({rel: lines(1500) for rel in SURFACE})
        self.assertEqual(result.returncode, 0, msg=result.stderr)
        self.assertNotIn("FILE SIZE LIMIT", result.stderr)

    def test_a_file_outside_the_gen2_surface_is_not_checked(self) -> None:
        result = self.check({"research_loops/big.py": lines(3000), "docs/gen2/BIG.md": lines(3000), "tools/other_tool.py": lines(3000)})
        self.assertEqual(result.returncode, 0, msg=result.stderr)

    def test_an_unlisted_generated_looking_file_fails(self) -> None:
        """Only the list exempts a file: not a GENERATED header, not the name
        of an allowlisted file in another directory."""
        header = "# GENERATED by tools/gen2_mutation_controls.py. Do not edit by hand.\n"
        result = self.check({"gen2/tests/gen2_mutation_controls.json": lines(1600), "tools/gen2_other_controls.json": header + lines(1600),
                             "deploy/gen2/gen2.env.example": header + lines(1600)})
        self.assertEqual(result.returncode, 1, msg=result.stderr)
        for rel, n in (("gen2/tests/gen2_mutation_controls.json", 1600), ("tools/gen2_other_controls.json", 1601), ("deploy/gen2/gen2.env.example", 1601)):
            with self.subTest(rel=rel):
                self.assertIn(f"FILE SIZE LIMIT EXCEEDED: {rel} has {n:,} lines", result.stderr)

    def test_an_allowlisted_generated_file_passes(self) -> None:
        result = self.check({"tools/gen2_mutation_controls.json": lines(12000), "deploy/gen2.env.example": lines(1600)})
        self.assertEqual(result.returncode, 0, msg=result.stderr)

    def test_an_allowlist_entry_whose_tool_does_not_name_it_fails(self) -> None:
        both = {rel: "{}\n" for rel in GENERATED} | {tool: f'OUT = "{rel}"\n' for rel, tool in GENERATED.items()}
        env, tool = "deploy/gen2.env.example", "tools/gen_source_catalog.py"
        cases = {  # a file on disk that git does not track is not one the repository holds
            "its tool is not tracked": (both, (tool,), f"{env}: listed as generated by {tool}, which is not a tracked file"),
            "its tool does not name it": (both | {tool: 'OUT = "deploy/other.env.example"\n'}, (), f"{env}: listed as generated by {tool}, which does not name it"),
            "it is not tracked": (both, (env,), f"{env}: listed as generated, but it is not a tracked file"),
        }
        for case, (files, untracked, expected) in cases.items():
            with self.subTest(case=case):
                result = self.check(files, generated=False, untracked=untracked)
                self.assertEqual(result.returncode, 1, msg=result.stderr)
                self.assertIn(f"GENERATED ALLOWLIST ENTRY DOES NOT HOLD: {expected}", result.stderr)

    def test_reaching_the_growth_review_trigger_fails(self) -> None:
        result = self.check({f"gen2/core/m{i}.py": lines(1500) for i in range(10)})  # 15,000 production lines, no file over the limit
        self.assertEqual(result.returncode, 1, msg=result.stderr)
        self.assertIn("GROWTH REVIEW REQUIRED: 15,000 production lines reach the 15,000-line trigger", result.stderr)
        self.assertNotIn("FILE SIZE LIMIT", result.stderr)

    def test_the_gateway_is_its_own_budget_not_the_engines(self) -> None:
        """15,000 gateway service lines trigger no engine growth review, and are reported on their own line."""
        files = {f"gateway/research_gateway/m{i}.py": lines(1500) for i in range(10)} | {"gateway/tests/test_m.py": lines(7)}
        result = self.check(files)
        self.assertEqual(result.returncode, 0, msg=result.stderr)
        self.assertNotIn("GROWTH REVIEW", result.stderr)
        self.assertIn("gateway service (its own budget, not in the trigger): production 15,000, tests 7", result.stdout)

    def test_below_the_growth_review_trigger_passes(self) -> None:
        files = {f"gen2/core/m{i}.py": lines(1500) for i in range(9)} | {"gen2/core/m9.py": lines(1499)}  # 14,999 production lines
        files |= {f"gen2/tests/test_m{i}.py": lines(1500) for i in range(4)}  # tests are not production
        result = self.check(files)
        self.assertEqual(result.returncode, 0, msg=result.stderr)
        self.assertNotIn("GROWTH REVIEW", result.stderr)


if __name__ == "__main__":
    unittest.main()
