"""Task 2b-repair-12: the gateway mutants that restate, for the schema-first decoder, the guards the earlier rounds put in each adapter by hand.

Before this task an adapter read a provider's payload field by field, so each guard was a line in an adapter (a `text()` here, a `preferred()` there) and each had a mutant
that removed it. Now every operation declares its payload (`SCHEMAS`, core/schema.py), one decoder checks the whole of it, and an adapter reads decoded values, so the guards
moved: the rules of the decoder (what is missing, null and malformed, and what a failure costs) are the mutants named D-*; what a MemberList and a Rec hand over is R8-*/R12-*;
and each alternative or typed field an adapter chooses between or reads by its truth is a field its schema declares, whose mutant declares it loosely (`any_()`) — and, where the
adapter also reads it eagerly itself, reads it lazily too: the guard had two layers there, and the old defect is both removed. A mutant has the earlier one's name where there
is one (its description and its killers are carried over); the A4-*-raw mutants restore the defect through the one door a MemberList leaves (`each`).

Not here, and why: R10-a-lazy-second-operand-is-added (the canary of the retired lazy-choice source scan: there is no scan, and an `or` over two decoded fields cannot skip
reading either); R9-bea-envelope-read-by-truth (a BEAAPI of false is D-a-falsy-value-is-left-out's); R8-sdmx-unreadable-series-container-is-empty and
R8-sdmx-datasets-garbage-is-none (D-a-malformed-entry-costs-the-answer and D-a-list-of-any-kind-is-a-list).
"""
from __future__ import annotations


def build(Mutant) -> list:
    """The mutants (tools/gen2_gateway_mutants.py: `Mutant`)."""
    return [
        Mutant('R8-opencitations-identity-each', 'OpenCitations takes its members out with each(), the identity builder, and builds from the list it gets back', 'research_gateway/adapters/opencitations.py',
               'members(SOURCE_ID, rows, lambda row: _link(key, row))}',
               '[r for r in (_link(key, row) for row in rows.each(lambda member: member)) if r is not OMIT]}',
               ('tests.test_member_decoding.EveryMemberAlone.test_a_member_that_is_not_an_object_costs_that_member_only', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.EveryMemberAlone.test_control_a_readable_member_alone_is_kept_whole', 'tests.test_member_decoding.ThroughTheRouter.test_control_readable_rows_are_complete')),
        Mutant('R8-opencitations-preprocess-before-decoder', "OpenCitations filters the rows with row.get(key) immediately before members() (Astra's rebuilt mutant: the old scan found nothing)", 'research_gateway/adapters/opencitations.py',
               'members(SOURCE_ID, rows, lambda row: _link(key, row))}',
               'members(SOURCE_ID, __import__("research_gateway.core.payload", fromlist=["MemberList"]).MemberList([row for row in rows.each(lambda member: member) if row.get(key)]), lambda row: _link(key, row))}',
               ('tests.test_member_decoding.EveryMemberAlone.test_a_member_that_is_not_an_object_costs_that_member_only', 'tests.test_member_decoding.ThroughTheRouter.test_one_unreadable_row_beside_a_readable_one_is_a_partial_lower_bound', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.EveryMemberAlone.test_control_a_readable_member_alone_is_kept_whole', 'tests.test_member_decoding.ThroughTheRouter.test_control_readable_rows_are_complete')),
        Mutant('R8-opencitations-metadata-first-row-raw', "OpenCitations' metadata lookup reads rows[0] itself instead of through first_member", 'research_gateway/adapters/opencitations.py',
               '        rec = first_member(SOURCE_ID, decode(SOURCE_ID, METADATA, resp.json), lambda m: _article(doi, m))\n',
               '        rows = decode(SOURCE_ID, METADATA, resp.json).each(lambda member: member)\n        rec = _article(doi, rows[0]) if rows else None\n',
               ('tests.test_member_decoding.FirstResult.test_an_unreadable_first_result_is_an_unreadable_answer', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.FirstResult.test_control_a_readable_first_result_is_the_record_and_none_is_not_found',)),
        Mutant('A4-semanticscholar-enrich-raw', 'Semantic Scholar builds its citation records by iterating the rows', 'research_gateway/adapters/semanticscholar.py',
               '"items": members(SOURCE_ID, decode(SOURCE_ID, SCHEMAS[f"enrich:{what}"], resp.json)["data"], lambda row: _linked(key, row))}',
               '"items": [r for r in (_linked(key, row) for row in decode(SOURCE_ID, SCHEMAS[f"enrich:{what}"], resp.json)["data"].each(lambda member: member)) if r is not OMIT]}',
               ('tests.test_member_decoding.EveryMemberAlone.test_a_member_that_is_not_an_object_costs_that_member_only', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.EveryMemberAlone.test_control_a_readable_member_alone_is_kept_whole',)),
        Mutant('A4-kaggle-listing-raw', 'Kaggle builds its file records by iterating the listing', 'research_gateway/adapters/kaggle.py',
               'records = members(SOURCE_ID, decode(SOURCE_ID, SCHEMAS["fetch"], resp.json)["datasetFiles"], lambda f: _file(identity, ref, f))',
               'records = [_file(identity, ref, f) for f in decode(SOURCE_ID, SCHEMAS["fetch"], resp.json)["datasetFiles"].each(lambda member: member)]',
               ('tests.test_member_decoding.EveryMemberAlone.test_a_member_that_is_not_an_object_costs_that_member_only', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.EveryMemberAlone.test_control_a_readable_member_alone_is_kept_whole',)),
        Mutant('A4-dataverse-listing-raw', 'Dataverse builds its file records by iterating the files, which also authorise a download', 'research_gateway/adapters/harvard_dataverse.py',
               'return members(source_id, d["latestVersion"]["files"], lambda f: _file(base, source_id, dataset, f))',
               'return [_file(base, source_id, dataset, f) for f in d["latestVersion"]["files"].each(lambda member: member)]',
               ('tests.test_member_decoding.EveryMemberAlone.test_a_member_that_is_not_an_object_costs_that_member_only', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.EveryMemberAlone.test_control_a_readable_member_alone_is_kept_whole', 'tests.test_member_decoding.DataverseDownloadMembership.test_a_file_that_is_not_in_the_dataset_is_refused_as_such')),
        Mutant('A4-bls-series-raw', 'BLS builds its series records by iterating the series', 'research_gateway/adapters/bls.py',
               'records = members(SOURCE_ID, j["Results"]["series"], _series)',
               'records = [_series(s) for s in j["Results"]["series"].each(lambda member: member)]',
               ('tests.test_member_decoding.EveryMemberAlone.test_a_member_that_is_not_an_object_costs_that_member_only', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.EveryMemberAlone.test_control_a_readable_member_alone_is_kept_whole',)),
        Mutant('A4-bis-series-raw', 'BIS builds its series records in a loop of its own (no series can fail here: only the source check sees it)', 'research_gateway/adapters/bis.py',
               '    records = members(SOURCE_ID, sdmx.series_xml(msg), record)',
               '    records = [record(s) for s in sdmx.series_xml(msg).each(lambda member: member)]',
               ('tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there',),
               ('tests.test_member_decoding.EveryMemberAlone.test_bis_series_are_decoded_through_the_one_decoder_too',)),
        Mutant('R8-sdmx-datasets-flattened', "ECB's data sets are flattened into series before any is decoded, so one malformed data set loses them all", 'research_gateway/core/sdmx.py',
               '    return datasets(msg).expand(lambda ds: ds["series"])',
               '    return MemberList([m for held in datasets(msg).each(lambda ds: ds["series"].each(lambda member: member)) for m in held])',
               ('tests.test_member_decoding.RoutedMixedAnswers.test_a_readable_series_survives_a_malformed_data_set', 'tests.test_member_decoding.EveryMemberAlone.test_a_member_that_is_not_an_object_costs_that_member_only', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.EveryMemberAlone.test_control_a_readable_member_alone_is_kept_whole', 'tests.test_member_decoding.RoutedMixedAnswers.test_control_readable_lists_are_complete')),
        Mutant('R8-hf-files-raw', "Hugging Face lists a dataset's files from the siblings in a loop of its own, so one malformed file loses them all", 'research_gateway/adapters/huggingface.py',
               'files = members(SOURCE_ID, d["siblings"], lambda sibling: _file(identity, repo, revision, rec["license"], sibling))',
               'files = [_file(identity, repo, revision, rec["license"], sibling) for sibling in d["siblings"].each(lambda member: member)]',
               ('tests.test_member_decoding.RoutedMixedAnswers.test_a_readable_file_survives_a_malformed_sibling', 'tests.test_member_decoding.EveryMemberAlone.test_a_member_that_is_not_an_object_costs_that_member_only', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.EveryMemberAlone.test_control_a_readable_member_alone_is_kept_whole', 'tests.test_member_decoding.RoutedMixedAnswers.test_control_readable_lists_are_complete')),
        Mutant('R8-hf-record-carries-the-files', "Hugging Face's dataset record copies its siblings into itself, so one malformed file loses the dataset", 'research_gateway/adapters/huggingface.py',
               '"file_count": None if d["siblings"] is None else len(d["siblings"])},',
               '"file_count": None if d["siblings"] is None else len(d["siblings"]), "files": [s["rfilename"] for s in (d["siblings"] or [])]},',
               ('tests.test_member_decoding.RoutedMixedAnswers.test_a_dataset_is_read_whole_beside_unreadable_files_in_every_lane_that_returns_it',),
               ('tests.test_member_decoding.RoutedMixedAnswers.test_control_readable_lists_are_complete',)),
        Mutant('A4-core-first-result-raw', 'CORE reads the first result in a lookup of its own', 'research_gateway/adapters/core.py',
               'return first_member(SOURCE_ID, decode(SOURCE_ID, SEARCH, resp.json)["results"], lambda w: _record(w, with_text=want_text))',
               'return (lambda r: _record(r[0], with_text=want_text) if r else None)(decode(SOURCE_ID, SEARCH, resp.json)["results"].each(lambda member: member))',
               ('tests.test_member_decoding.FirstResult.test_an_unreadable_first_result_is_an_unreadable_answer', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.FirstResult.test_control_a_readable_first_result_is_the_record_and_none_is_not_found',)),
        Mutant('A4-doaj-article-first-result-raw', 'DOAJ reads the first article result in a lookup of its own', 'research_gateway/adapters/doaj.py',
               'return first_member(SOURCE_ID, decode(SOURCE_ID, RESOLVE_ARTICLE, resp.json)["results"], _record)',
               'return (lambda r: _record(r[0]) if r else None)(decode(SOURCE_ID, RESOLVE_ARTICLE, resp.json)["results"].each(lambda member: member))',
               ('tests.test_member_decoding.FirstResult.test_an_unreadable_first_result_is_an_unreadable_answer', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.FirstResult.test_control_a_readable_first_result_is_the_record_and_none_is_not_found',)),
        Mutant('A4-doaj-journal-first-result-raw', 'DOAJ reads the first journal result in a lookup of its own', 'research_gateway/adapters/doaj.py',
               'return first_member(SOURCE_ID, decode(SOURCE_ID, RESOLVE_JOURNAL, resp.json)["results"], lambda a: _journal(issn, a))',
               'return (lambda r: _journal(issn, r[0]) if r else None)(decode(SOURCE_ID, RESOLVE_JOURNAL, resp.json)["results"].each(lambda member: member))',
               ('tests.test_member_decoding.FirstResult.test_an_unreadable_first_result_is_an_unreadable_answer', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.FirstResult.test_control_a_readable_first_result_is_the_record_and_none_is_not_found',)),
        Mutant('A4-europepmc-first-result-raw', 'Europe PMC reads the first result in a lookup of its own', 'research_gateway/adapters/europepmc.py',
               'return first_member(SOURCE_ID, decode(SOURCE_ID, RESOLVE, resp.json)["resultList"]["result"], _record)',
               'return (lambda r: _record(r[0]) if r else None)(decode(SOURCE_ID, RESOLVE, resp.json)["resultList"]["result"].each(lambda member: member))',
               ('tests.test_member_decoding.FirstResult.test_an_unreadable_first_result_is_an_unreadable_answer', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.FirstResult.test_control_a_readable_first_result_is_the_record_and_none_is_not_found',)),
        Mutant('A4-openaire-first-result-raw', 'OpenAIRE reads the first result in a lookup of its own', 'research_gateway/adapters/openaire.py',
               'return first_member(SOURCE_ID, decode(SOURCE_ID, RESOLVE, resp.json)["results"], _record)',
               'return (lambda r: _record(r[0]) if r else None)(decode(SOURCE_ID, RESOLVE, resp.json)["results"].each(lambda member: member))',
               ('tests.test_member_decoding.FirstResult.test_an_unreadable_first_result_is_an_unreadable_answer', 'tests.test_member_isolation.Reads.test_every_place_an_answer_leaves_the_decoder_is_listed_with_its_reason_and_every_listed_use_is_there'),
               ('tests.test_member_decoding.FirstResult.test_control_a_readable_first_result_is_the_record_and_none_is_not_found',)),
        Mutant('R8-views-allow-iteration', 'a MemberList can be iterated again', 'research_gateway/core/payload.py',
               '        raise TypeError(f"a MemberList cannot be iterated: {_LIST_USE}")\n\n    def __reversed__(self):',
               '        return iter(self._items)\n\n    def __reversed__(self):',
               ('tests.test_member_isolation.Bypasses.test_each_shape_is_impossible_against_a_providers_list', 'tests.test_member_isolation.Views.test_a_list_cannot_be_iterated_indexed_sliced_or_searched'),
               ('tests.test_member_isolation.Views.test_each_member_is_read_alone', 'tests.test_member_isolation.Bypasses.test_the_helpers_refuse_a_plain_list')),
        Mutant('R8-views-allow-indexing', 'a MemberList can be indexed and sliced again', 'research_gateway/core/payload.py',
               '        raise TypeError(f"a MemberList cannot be indexed or sliced: {_LIST_USE}")',
               '        return self._items[_]',
               ('tests.test_member_isolation.Bypasses.test_each_shape_is_impossible_against_a_providers_list', 'tests.test_member_isolation.Views.test_a_list_cannot_be_iterated_indexed_sliced_or_searched'),
               ('tests.test_member_isolation.Views.test_each_member_is_read_alone', 'tests.test_member_isolation.Bypasses.test_the_helpers_refuse_a_plain_list')),
        Mutant('R8-records-can-be-walked', 'a Rec can be walked by its field names again', 'research_gateway/core/payload.py',
               '        raise TypeError("a Rec is read by its declared field names; it is not iterated")',
               '        return iter(self._v)',
               ('tests.test_member_isolation.Views.test_an_object_holds_its_declared_fields_and_nothing_else', 'tests.test_schema.Records.test_a_record_is_read_by_its_declared_names_and_is_not_a_collection'),
               ('tests.test_member_isolation.Views.test_each_member_is_read_alone',)),
        Mutant('R12-an-undeclared-read-returns-nothing', 'a field an adapter reads and its schema does not declare reads as None', 'research_gateway/core/payload.py',
               '        except KeyError:\n            raise UndeclaredRead(',
               '        except KeyError:\n            return None\n            raise UndeclaredRead(',
               ('tests.test_member_isolation.Views.test_an_object_holds_its_declared_fields_and_nothing_else', 'tests.test_schema.Records.test_a_record_is_read_by_its_declared_names_and_is_not_a_collection', 'tests.test_schema_corruption.UndeclaredReads.test_a_field_an_adapter_reads_and_its_schema_does_not_declare_is_a_failure_and_not_a_lost_member'),
               ('tests.test_member_isolation.Views.test_each_member_is_read_alone',)),
        Mutant('R12-an-undeclared-read-is-a-members-loss', "an undeclared read is an error a member builder swallows, so the adapter's mistake costs a member", 'research_gateway/core/payload.py',
               'class UndeclaredRead(RuntimeError):',
               'class UndeclaredRead(KeyError):',
               ('tests.test_schema.Records.test_an_undeclared_read_is_not_any_error_a_member_builder_swallows', 'tests.test_member_isolation.Views.test_an_object_holds_its_declared_fields_and_nothing_else', 'tests.test_schema_corruption.UndeclaredReads.test_a_field_an_adapter_reads_and_its_schema_does_not_declare_is_a_failure_and_not_a_lost_member'),
               ('tests.test_member_isolation.Views.test_each_member_is_read_alone',)),
        Mutant('R8-expand-drops-the-unreadable-holder', 'a member that cannot be unfolded vanishes instead of counting as one loss', 'research_gateway/core/payload.py',
               '                out.append(member if isinstance(member, Unreadable) else Unreadable(str(e), member))',
               '                pass',
               ('tests.test_member_isolation.Views.test_members_held_by_members_unfold_with_each_unreadable_holder_one_loss', 'tests.test_member_isolation.Sdmx.test_the_helpers_take_and_give_decoded_values'),
               ('tests.test_member_isolation.Views.test_each_member_is_read_alone', 'tests.test_member_decoding.RoutedMixedAnswers.test_control_readable_lists_are_complete')),
        Mutant('A4-first-result-answered-by-the-next', 'a lookup whose first result cannot be read answers with the next readable one', 'research_gateway/core/payload.py',
               '        got = MemberList(self._items[:1]).each(build)\n',
               '        got = [r for r in self.each(build) if r][:1]\n',
               ('tests.test_member_decoding.FirstResult.test_an_unreadable_first_result_is_an_unreadable_answer', 'tests.test_member_isolation.Views.test_the_first_member_is_read_like_any_other_and_never_replaced_by_the_next'),
               ('tests.test_member_decoding.FirstResult.test_control_a_readable_first_result_is_the_record_and_none_is_not_found',)),
        Mutant('P-need-lenient', 'a required container that is missing reads as empty', 'research_gateway/core/schema.py',
               '    if fs.required:\n',
               '    if False:\n',
               ('tests.test_payload_shapes.AdapterBoundary.test_an_unreadable_success_is_never_an_empty_answer', 'tests.test_schema.Containers.test_required_means_there_and_not_null'),
               ('tests.test_payload_shapes.AdapterBoundary.test_control_the_apis_own_empty_answer_stays_empty',)),
        Mutant('P-sdmx-lenient', 'unparseable SDMX-ML reads as an empty message', 'research_gateway/core/schema.py',
               '        raise PayloadError(f"unparseable SDMX-ML ({e})") from None',
               '        return ET.Element("StructureSpecificData")',
               ('tests.test_adapters_statistical.BisEcb.test_bis_reads_sdmx_ml', 'tests.test_schema.Xml.test_a_message_that_is_not_xml_or_not_of_the_kind_asked_for_is_unreadable'),
               ('tests.test_payload_shapes.AdapterBoundary.test_control_the_apis_own_empty_answer_stays_empty',)),
        Mutant('D-a-message-of-another-kind-is-read', 'an SDMX document that is not a message of the kind asked for is read as one', 'research_gateway/core/schema.py',
               '    if _local(root.tag) not in roots:\n',
               '    if False:\n',
               ('tests.test_schema.Xml.test_a_message_that_is_not_xml_or_not_of_the_kind_asked_for_is_unreadable', 'tests.test_adapters_statistical.BisEcb.test_bis_reads_sdmx_ml'),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-text-falsy-is-nothing', 'a provider text field that is false, 0, [] or {} is read as no text', 'research_gateway/core/schema.py',
               '        if v is None or isinstance(v, str):\n            return v\n        raise _bad(at, v, "text")',
               '        if not v or isinstance(v, str):\n            return v\n        raise _bad(at, v, "text")',
               ('tests.test_schema.Leaves.test_text_is_text_or_nothing', 'tests.test_invariants.Corruptions.test_b_an_unreadable_container_is_never_empty__crossref_find__a_full_page'),
               ('tests.test_present_means_typed.Records.test_control_the_fields_that_are_right_are_kept_and_nothing_is_nothing',)),
        Mutant('D-key-accepts-a-blank-name', 'a blank string names a member', 'research_gateway/core/schema.py',
               '        if (isinstance(v, str) and v.strip()) or (isinstance(v, int) and not isinstance(v, bool)):\n            return v   # as sent',
               '        if isinstance(v, str) or (isinstance(v, int) and not isinstance(v, bool)):\n            return v   # as sent',
               ('tests.test_schema.Leaves.test_a_key_is_what_a_provider_names_a_member_by_as_sent',),
               ('tests.test_schema.Leaves.test_text_is_text_or_nothing',)),
        Mutant('D-key-accepts-a-boolean', 'a boolean names a member', 'research_gateway/core/schema.py',
               '        if (isinstance(v, str) and v.strip()) or (isinstance(v, int) and not isinstance(v, bool)):\n            return v   # as sent',
               '        if (isinstance(v, str) and v.strip()) or isinstance(v, int):\n            return v   # as sent',
               ('tests.test_schema.Leaves.test_a_key_is_what_a_provider_names_a_member_by_as_sent',),
               ('tests.test_schema.Leaves.test_text_is_text_or_nothing',)),
        Mutant('D-flag-by-truth', 'a flag that is 0, "", [] or "no" is read by its truth', 'research_gateway/core/schema.py',
               '        if v is None or isinstance(v, bool):\n            return bool(v)\n        raise _bad(at, v, "a flag")',
               '        return bool(v)',
               ('tests.test_schema.Leaves.test_a_flag_is_true_or_false_and_false_when_left_out', 'tests.test_typed_fields.RestrictionsAreReadAsWhatTheyAre.test_a_flag_is_read_as_one'),
               ('tests.test_schema.Leaves.test_text_is_text_or_nothing',)),
        Mutant('D-whole-number-accepts-a-boolean', 'a boolean is a whole number', 'research_gateway/core/schema.py',
               '        if v is None or (isinstance(v, int) and not isinstance(v, bool)):\n            return v\n        raise _bad(at, v, "a whole number")',
               '        if v is None or isinstance(v, int):\n            return v\n        raise _bad(at, v, "a whole number")',
               ('tests.test_schema.Leaves.test_a_whole_number_is_not_a_boolean_a_float_or_text',),
               ('tests.test_schema.Leaves.test_text_is_text_or_nothing',)),
        Mutant('D-a-year-is-anything', 'a value that is no year reads as none', 'research_gateway/core/schema.py',
               '    raise PayloadError(f"a year is {_kind(value)} {value!r}, not a year")',
               '    return None',
               ('tests.test_schema.Leaves.test_a_year_is_a_whole_number_the_digits_of_one_or_an_integral_float',),
               ('tests.test_schema.Leaves.test_text_is_text_or_nothing',)),
        Mutant('D-token-of-any-kind', 'a paging cursor that is a list, an object, a number or a boolean is passed on as if it were read', 'research_gateway/core/schema.py',
               '        if isinstance(v, str) and v.strip():\n            return v\n        raise _bad(at, v, "a cursor")',
               '        return v',
               ('tests.test_provider_pagination.UnreadableMetadataNeverEnds.test_a_cursor_that_cannot_be_read_continues_nothing_and_ends_nothing', 'tests.test_schema.Leaves.test_a_token_is_a_non_blank_string'),
               ('tests.test_provider_pagination.UnreadableMetadataNeverEnds.test_control_the_readable_forms_still_end_and_continue',)),
        Mutant('D-token-accepts-numbers', 'a cursor that is a number is a continuation, and a cursor of 0 restarts the listing', 'research_gateway/core/schema.py',
               '        if isinstance(v, str) and v.strip():\n            return v\n        raise _bad(at, v, "a cursor")',
               '        if isinstance(v, (str, int)) and not isinstance(v, bool):\n            return v\n        raise _bad(at, v, "a cursor")',
               ('tests.test_invariants.Corruptions.test_a_ends_or_continues_only_on_what_it_read__crossref_find__a_full_page', 'tests.test_invariants.Corruptions.test_a_ends_or_continues_only_on_what_it_read__europepmc_find'),
               ('tests.test_provider_pagination.Crossref.test_continues',)),
        Mutant('D-a-falsy-value-is-left-out', 'a container that is false, 0, empty text or an empty object is read as one the provider left out', 'research_gateway/core/schema.py',
               '    if raw is MISSING or raw is None:\n        return _absent(fs, at, parent, raw is MISSING)',
               '    if raw is MISSING or not raw:\n        return _absent(fs, at, parent, raw is MISSING)',
               ('tests.test_present_means_typed.HoldersOfMembers.test_hf_siblings_that_are_there_and_not_a_list_are_unreadable_not_empty', 'tests.test_present_means_typed.HoldersOfMembers.test_a_reference_list_that_is_there_and_not_a_list_is_unreadable', 'tests.test_schema.Containers.test_a_list_left_out_or_null_is_empty_and_any_other_kind_is_unreadable', 'tests.test_typed_fields.CatalogueEntries.test_bea_an_envelope_that_is_not_an_object_is_unreadable_and_reports_no_error', 'tests.test_invariants.Corruptions.test_b_an_unreadable_container_is_never_empty__crossref_enrich_references'),
               ('tests.test_present_means_typed.HoldersOfMembers.test_hf_control_siblings_that_are_left_out_or_empty_list_no_files', 'tests.test_present_means_typed.HoldersOfMembers.test_ecb_control_a_series_that_is_left_out_or_is_an_empty_object_lists_nothing')),
        Mutant('D-a-count-that-is-not-zero-says-nothing-matched', 'a count of false, 0.0 or an empty list lets the provider leave its results out', 'research_gateway/core/schema.py',
               '    return type(value) is int and value == 0',
               '    return value == 0 and not isinstance(value, str)',
               ('tests.test_present_means_typed.Readers.test_only_the_whole_number_zero_says_nothing_matched', 'tests.test_present_means_typed.ListsLeftOutWhenNothingMatched.test_a_list_that_is_left_out_is_empty_only_when_the_count_is_the_whole_number_zero', 'tests.test_invariants.Corruptions.test_b_an_unreadable_container_is_never_empty__govinfo_find'),
               ('tests.test_schema.Leaves.test_a_whole_number_is_not_a_boolean_a_float_or_text',)),
        Mutant('D-a-list-may-always-be-left-out', 'a list a provider leaves out reads as empty whatever its count says', 'research_gateway/core/schema.py',
               '    if fs.empty_when is not None:\n',
               '    if False:\n',
               ('tests.test_schema.Containers.test_a_list_may_be_left_out_only_when_the_provider_counts_nothing', 'tests.test_present_means_typed.ListsLeftOutWhenNothingMatched.test_a_list_that_is_left_out_is_empty_only_when_the_count_is_the_whole_number_zero'),
               ('tests.test_schema.Containers.test_required_means_there_and_not_null',)),
        Mutant('D-a-list-of-any-kind-is-a-list', 'a value that is not a list reads as an empty one', 'research_gateway/core/schema.py',
               '    if not isinstance(v, list):\n        raise _bad(at, v, "a list")\n    if s.at_most',
               '    if not isinstance(v, list):\n        return []\n    if s.at_most',
               ('tests.test_schema.Containers.test_a_list_left_out_or_null_is_empty_and_any_other_kind_is_unreadable', 'tests.test_present_means_typed.HoldersOfMembers.test_hf_siblings_that_are_there_and_not_a_list_are_unreadable_not_empty'),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-an-object-of-any-kind-is-an-object', 'a value that is not an object reads as an empty one', 'research_gateway/core/schema.py',
               '    if not isinstance(v, (dict, ET.Element)):\n        raise _bad(at, v, "an object")\n    values = {}',
               '    if not isinstance(v, (dict, ET.Element)):\n        v = {}\n    values = {}',
               ('tests.test_schema.Containers.test_an_object_must_be_one_and_holds_exactly_its_declared_fields', 'tests.test_invariants.Corruptions.test_b_an_unreadable_container_is_never_empty__crossref_find__a_full_page'),
               ('tests.test_schema.Containers.test_an_object_left_out_or_null_is_an_object_of_nothing',)),
        Mutant('D-a-malformed-member-costs-the-answer', 'a member that cannot be decoded loses the whole list instead of itself', 'research_gateway/core/schema.py',
               '            except PayloadError as e:\n                out.append(Unreadable(str(e), m))',
               '            except ZeroDivisionError as e:\n                out.append(Unreadable(str(e), m))',
               ('tests.test_member_decoding.EveryMemberAlone.test_a_member_that_is_not_an_object_costs_that_member_only',),
               ('tests.test_member_decoding.EveryMemberAlone.test_control_a_readable_member_alone_is_kept_whole',)),
        Mutant('D-a-malformed-entry-costs-the-answer', 'an entry of a keyed container that cannot be decoded loses the whole container instead of itself', 'research_gateway/core/schema.py',
               '            except PayloadError as e:\n                out.append(Unreadable(str(e), val))',
               '            except ZeroDivisionError as e:\n                out.append(Unreadable(str(e), val))',
               ('tests.test_invariants.Corruptions.test_c_readable_peers_survive__ecb_data',),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-an-isolated-field-costs-the-answer', 'a field declared isolated loses the answer when it cannot be read', 'research_gateway/core/schema.py',
               '        except PayloadError as e:\n            return Unreadable(str(e), None if raw is MISSING else raw)',
               '        except ZeroDivisionError as e:\n            return Unreadable(str(e), None if raw is MISSING else raw)',
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_unpaywall_a_best_location_that_cannot_be_read_costs_completeness_and_not_the_listed_locations',),
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_unpaywall_control_the_best_location_stands_in_for_none_listed_and_is_otherwise_left_alone',)),
        Mutant('D-a-soft-field-costs-the-answer', 'a field declared soft loses the answer when it cannot be read', 'research_gateway/core/schema.py',
               '    if fs.kind == "soft":\n        try:\n            return _field(fs.of, raw, at, parent)\n        except PayloadError:\n            return None',
               '    if fs.kind == "soft":\n        try:\n            return _field(fs.of, raw, at, parent)\n        except ZeroDivisionError:\n            return None',
               ('tests.test_invariants.Corruptions.test_c_readable_peers_survive__crossref_find__a_full_page',),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-a-deep-field-costs-the-answer', 'a metadata field read through containers loses the answer when a container cannot be read', 'research_gateway/core/schema.py',
               '    path, leaf = fs.of\n    for step in path:\n        v = v.get(step) if isinstance(v, dict) else None\n    try:\n        return None if v is None else _decode(leaf, v, at)\n    except PayloadError:\n        return None',
               '    path, leaf = fs.of\n    for step in path:\n        v = v.get(step)\n    try:\n        return None if v is None else _decode(leaf, v, at)\n    except PayloadError:\n        return None',
               ('tests.test_invariants.Corruptions.test_c_readable_peers_survive__datacite_find__a_full_page',),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-a-bare-object-may-be-empty', 'an empty object stands for a list of one row', 'research_gateway/core/schema.py',
               '    if isinstance(v, dict) and v and s.bare:',
               '    if isinstance(v, dict) and s.bare:',
               ('tests.test_schema.Containers.test_a_bare_object_stands_for_a_list_of_one_only_where_the_schema_says_so_and_only_when_it_holds_something',),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-a-list-may-hold_any_number', 'a list holds more than the schema allows', 'research_gateway/core/schema.py',
               '    if s.at_most is not None and len(v) > s.at_most:',
               '    if False:',
               ('tests.test_schema.Containers.test_a_list_holds_at_most_what_the_schema_allows',),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-oneof-is-the-first-kind-that-fails-open', 'a value that is none of the kinds a field may be reads as the last', 'research_gateway/core/schema.py',
               '            except PayloadError as e:\n                problems.append(str(e))\n        raise PayloadError(" / ".join(problems))',
               '            except PayloadError as e:\n                problems.append(str(e))\n        return v',
               ('tests.test_schema.Containers.test_oneof_is_the_first_kind_that_reads_and_unreadable_when_none_does',),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-a-lookup-reads-no-element', "a lookup's first element is carried without being decoded", 'research_gateway/core/schema.py',
               '        return _decode(s.of, v[0], at + (0,)) if v else None',
               '        return v[0] if v else None',
               ('tests.test_schema.Containers.test_a_lookup_reads_its_first_element_whole_and_nothing_after_it', 'tests.test_alternatives.NestedAlternatives.test_sdmx_json_every_place_a_structure_is_stated_is_decoded_beside_a_valid_one'),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-a-field-is-read-as-the-same-kind-whatever-its-sibling-says', 'a field that depends on its sibling is read as the default kind', 'research_gateway/core/schema.py',
               '            fs = variants.get(sibling, other) if isinstance(sibling, str) else other',
               '            fs = other',
               ('tests.test_schema.Containers.test_a_field_that_depends_on_a_sibling_is_read_as_the_sibling_says',),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-a-table-value-is-not-decoded', "the values of a keyed container that is one record's own data are carried as sent", 'research_gateway/core/schema.py',
               '            return {name: _decode(s.of, val, at + (name,)) for name, val in v.items()}',
               '            return dict(v)',
               ('tests.test_schema.Containers.test_entries_are_a_keyed_containers_members_and_a_table_is_one_records_own_data',),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-the-elements-of-an-own-list-are-not-decoded', "the elements of a record's own list are carried as sent", 'research_gateway/core/schema.py',
               '            out = [_decode(s.of, m, at + (i,)) for i, m in enumerate(items)]',
               '            out = list(items)',
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',),
               ('tests.test_schema.Containers.test_an_object_must_be_one_and_holds_exactly_its_declared_fields',)),
        Mutant('D-a-rule-is-not-applied', "the rule that ties an object's fields together is not applied", 'research_gateway/core/schema.py',
               '    if s.rule is not None:\n        try:\n            s.rule(rec)',
               '    if False:\n        try:\n            s.rule(rec)',
               ('tests.test_schema.Containers.test_a_rule_ties_fields_together_and_its_refusal_is_the_objects',),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-a-required-field-may-be-null', 'a required field that is null reads as empty', 'research_gateway/core/schema.py',
               '        raise PayloadError(f"{_where(at)}: the answer has no {_where(at)}" if missing else f"{_where(at)} is null where a value belongs")',
               '        if missing:\n            raise PayloadError(f"{_where(at)}: the answer has no {_where(at)}")',
               ('tests.test_schema.Containers.test_required_means_there_and_not_null',),
               ('tests.test_schema.Containers.test_an_own_list_is_all_or_nothing',)),
        Mutant('D-a-field-left-out-takes-the-last-default', 'a field that is null takes the default of one that is left out', 'research_gateway/core/schema.py',
               '    if fs.kind == "any" and missing:\n        return fs.default',
               '    if fs.kind == "any":\n        return fs.default',
               ('tests.test_schema.Leaves.test_any_is_carried_as_sent_and_its_default_is_for_a_field_that_is_left_out_not_null',),
               ('tests.test_schema.Leaves.test_text_is_text_or_nothing',)),
        Mutant('R10-datacite-rights-second-spelling-not-read', "DataCite's `rights` is never decoded: it is read only when `rightsIdentifier` says nothing", 'research_gateway/adapters/datacite.py',
               'RIGHT = S.obj({"rightsIdentifier": S.text(), "rights": S.text()}',
               'RIGHT = S.obj({"rightsIdentifier": S.text(), "rights": S.any_()}',
               ('tests.test_oracle.FallbackAlternatives.test_a_malformed_alternate_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_oracle.FallbackAlternatives.test_with_both_populated_and_valid_the_answer_is_read_whole', 'tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read')),
        Mutant('R10-bea-description-second-spelling-not-read', "BEA's `Description` is never decoded: it is read only when `Desc` says nothing", 'research_gateway/adapters/bea.py',
               '"Desc": S.text(), "Description": S.text(),',
               '"Desc": S.text(), "Description": S.any_(),',
               ('tests.test_oracle.FallbackAlternatives.test_a_malformed_alternate_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_oracle.FallbackAlternatives.test_with_both_populated_and_valid_the_answer_is_read_whole', 'tests.test_typed_fields.CatalogueEntries.test_bea_control_the_description_that_is_there_is_the_label')),
        Mutant('R10-datacite-id-read-only-when-no-doi', "a DataCite record's own id is never decoded: it is read only when it states no DOI", 'research_gateway/adapters/datacite.py',
               ('DOI_RECORD = S.obj({"id": S.text(),', '    stated, own = normalize_doi(a["doi"]), normalize_doi(d["id"])   # the registry\'s own id is its DOI: both are read as identifiers before either is chosen\n    doi = own if a["doi"] in (None, "") else stated   # an empty one is none'),
               ('DOI_RECORD = S.obj({"id": S.any_(),', '    stated = a["doi"]\n    doi = normalize_doi(d["id"] if stated is None or stated == "" else stated)   # an empty one is none'),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-bea-title-second-field-not-read', "BEA's `LineDescription` is never decoded: it is read only when `TableName` says nothing", 'research_gateway/adapters/bea.py',
               'TABLE_ROW = S.obj({"TableName": S.text(), "LineDescription": S.text()})',
               'TABLE_ROW = S.obj({"TableName": S.text(), "LineDescription": S.any_()})',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-bea-value-key-first-spelling-wins', "a BEA value row's other key spellings are never decoded: only the parameter's own is", 'research_gateway/adapters/bea.py',
               'spellings = {name: S.maybe_key(only_empty=True) for name in (parameter, parameter.capitalize(), parameter.upper(), "Key")}',
               'spellings = {name: (S.maybe_key(only_empty=True) if name == parameter else S.any_()) for name in (parameter, parameter.capitalize(), parameter.upper(), "Key")}',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-bea-listing-first-key-wins', "BEA's listing keys other than the first are never decoded", 'research_gateway/adapters/bea.py',
               'DATA_LIST = _answer({**{k: _rows(TABLE_ROW) for k in LISTING_KEYS}, "Notes": NOTES}, _stated())',
               'DATA_LIST = _answer({**{k: (_rows(TABLE_ROW) if k == "Dataset" else S.maybe(S.any_())) for k in LISTING_KEYS}, "Notes": NOTES}, _stated())',
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_bea_every_listing_key_the_answer_carries_is_read_before_the_first_is_chosen',),
               ('tests.test_typed_fields.CatalogueEntries.test_bea_control_the_description_that_is_there_is_the_label',)),
        Mutant('R10-bea-error-in-the-envelope-not-read', "BEA's envelope-level error is never decoded: it is read as it is sent, when the results state none", 'research_gateway/adapters/bea.py',
               ('return S.obj({"BEAAPI": S.obj({"Results": S.maybe(S.obj({**results, "Error": ERROR})), "Error": ERROR})}, rule=rule)', '    return (beside if beside is not None and beside.raw else api["Error"])["APIErrorDescription"]'),
               ('return S.obj({"BEAAPI": S.obj({"Results": S.maybe(S.obj({**results, "Error": ERROR})), "Error": S.any_()})}, rule=rule)', '    return beside["APIErrorDescription"] if beside is not None and beside.raw else (api["Error"].get("APIErrorDescription") if isinstance(api["Error"], dict) else None)'),
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_bea_an_error_stated_in_either_place_is_read_whichever_the_answer_chose',),
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_bea_an_error_that_one_place_states_is_reported_whatever_the_other_holds',)),
        Mutant('R10-crossref-name-read-only-without-given-family', "a Crossref author's `name` is never decoded: it is read only when there is no given or family name", 'research_gateway/adapters/crossref.py',
               'AUTHOR = S.obj({"given": S.text(), "family": S.text(), "name": S.text()}',
               'AUTHOR = S.obj({"given": S.text(), "family": S.text(), "name": S.any_()}',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-crossref-created-read-only-without-issued', "a Crossref work's creation date is never decoded: it is read only when it states no issue date", 'research_gateway/adapters/crossref.py',
               ('"created": S.obj({"date-time": S.text()})', '    created = year_from(w["created"]["date-time"])\n', 'else created\n'),
               ('"created": S.obj({"date-time": S.any_()})', '', 'else year_from(w["created"]["date-time"])\n'),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-dataverse-entity-id-read-only-without-doi', "a Dataverse hit's entity id is never decoded: it is read only when it states no DOI", 'research_gateway/adapters/harvard_dataverse.py',
               'HIT = S.obj({"global_id": S.text(), "entity_id": S.maybe_key(),',
               'HIT = S.obj({"global_id": S.text(), "entity_id": S.any_(),',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-dataverse-dataset-id-read-only-without-doi', "a Dataverse dataset's id is never decoded: it is read only when it states no DOI", 'research_gateway/adapters/harvard_dataverse.py',
               '_DATASET = {"id": S.maybe_key(), "identifier"',
               '_DATASET = {"id": S.any_(), "identifier"',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-dataverse-file-name-read-only-without-label', "a Dataverse file's name is never decoded: it is read only when it has no label", 'research_gateway/adapters/harvard_dataverse.py',
               '"dataFile": S.obj({"id": S.key(), "filename": S.text(),',
               '"dataFile": S.obj({"id": S.key(), "filename": S.any_(),',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-doaj-own-id-read-only-without-doi', "a DOAJ article's own id is never decoded: it is read only when it lists no DOI", 'research_gateway/adapters/doaj.py',
               'ARTICLE = S.obj({"id": S.maybe_key(),',
               'ARTICLE = S.obj({"id": S.any_(),',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-doaj-only-the-first-doi-is-read', "a DOAJ article's later DOI identifiers are never read", 'research_gateway/adapters/doaj.py',
               ('"identifier": S.own(S.obj({"type": S.text(), "id": S.text()}))', '    dois = [normalize_doi(i["id"]) for i in b["identifier"] if (i["type"] or "").lower() == "doi"]   # every DOI it lists is read\n    doi = dois[0] if dois else None'),
               ('"identifier": S.own(S.obj({"type": S.text(), "id": S.any_()}))', '    doi = next((normalize_doi(i["id"]) for i in b["identifier"] if (i["type"] or "").lower() == "doi"), None)'),
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_doaj_every_doi_an_article_lists_is_read',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-europepmc-source-read-only-with-an-id', "a Europe PMC record's source is never decoded: it is read only when it has an id", 'research_gateway/adapters/europepmc.py',
               '"id": S.text(), "source": S.text(),',
               '"id": S.text(), "source": S.any_(),',
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_europepmc_the_source_is_read_even_when_the_id_that_needs_it_is_missing',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-core-id-read-only-without-doi', "a CORE work's id is never decoded: it is read only when it states no DOI", 'research_gateway/adapters/core.py',
               'WORK = S.obj({"doi": S.text(), "id": S.maybe_key(),',
               'WORK = S.obj({"doi": S.text(), "id": S.any_(),',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-openaire-id-read-only-without-doi', "an OpenAIRE record's own id is never decoded: it is read only when it lists no DOI", 'research_gateway/adapters/openaire.py',
               'PRODUCT = S.obj({"id": S.maybe_key(),',
               'PRODUCT = S.obj({"id": S.any_(),',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-openaire-only-the-first-doi-is-read', "an OpenAIRE record's later DOI identifiers are never read", 'research_gateway/adapters/openaire.py',
               ('PID = S.obj({"scheme": S.text(), "value": S.text()})', '    dois = [normalize_doi(p["value"]) for p, scheme in zip(pids, schemes) if scheme == "doi"]   # every DOI it lists is read; the first that is one is its DOI\n    doi = next((d for d in dois if d), None)'),
               ('PID = S.obj({"scheme": S.text(), "value": S.any_()})', '    doi = next((normalize_doi(p["value"]) for p, scheme in zip(pids, schemes) if scheme == "doi" and normalize_doi(p["value"])), None)'),
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_openaire_every_doi_a_record_lists_is_read',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-socrata-link-read-only-without-permalink', "a Socrata hit's `link` is never decoded: it is read only when it has no permalink", 'research_gateway/adapters/socrata.py',
               '"permalink": S.text(), "link": S.text()}',
               '"permalink": S.text(), "link": S.any_()}',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-unpaywall-url-read-only-without-a-pdf', "an Unpaywall location's `url` is never decoded: it is read only when it has no PDF link", 'research_gateway/adapters/unpaywall.py',
               'LOCATION = S.obj({"url_for_pdf": S.text(), "url": S.text(),',
               'LOCATION = S.obj({"url_for_pdf": S.text(), "url": S.any_(),',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-unpaywall-unreadable-best-location-costs-the-listed-ones', 'a best location that cannot be read makes the listed locations unreadable too', 'research_gateway/adapters/unpaywall.py',
               '"best_oa_location": S.isolated(LOCATION)',
               '"best_oa_location": LOCATION',
               ('tests.test_invariants.Corruptions.test_c_readable_peers_survive__unpaywall_enrich_oa_location', 'tests.test_alternatives.OtherFormsOfTheSameShape.test_unpaywall_a_best_location_that_cannot_be_read_costs_completeness_and_not_the_listed_locations'),
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_unpaywall_control_the_best_location_stands_in_for_none_listed_and_is_otherwise_left_alone',)),
        Mutant('R10-huggingface-created-read-only-without-modified', "a Hugging Face repository's creation date is never decoded: it is read only when it states no modification date", 'research_gateway/adapters/huggingface.py',
               '"lastModified": S.text(), "createdAt": S.text(),',
               '"lastModified": S.text(), "createdAt": S.any_(),',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-huggingface-tags-read-only-without-a-card-licence', "a Hugging Face repository's tags are never decoded: they are read only when its card states no licence", 'research_gateway/adapters/huggingface.py',
               '"tags": S.own(S.any_()), "gated"',
               '"tags": S.any_(default=[]), "gated"',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read', 'tests.test_present_means_typed.DatasetFiles.test_a_garbled_author_or_tags_or_title_does_not_cost_the_files_of_a_hugging_face_repository')),
        Mutant('R10-kaggle-size-read-only-without-total-bytes', "a Kaggle file's `size` is never decoded: it is read only when it states no total bytes", 'research_gateway/adapters/kaggle.py',
               '"totalBytes": S.whole(), "size": S.whole(),',
               '"totalBytes": S.whole(), "size": S.any_(),',
               ('tests.test_alternatives.AlternativesBesideEachOther.test_an_alternate_of_the_wrong_kind_beside_a_valid_preferred_value_is_not_ignored',),
               ('tests.test_alternatives.AlternativesBesideEachOther.test_the_valid_alternate_alone_and_the_valid_preferred_alone_are_read',)),
        Mutant('R10-sdmx-structures-read-only-without-a-structure', "an SDMX-JSON message's `structures` is never decoded: it is read only when it has no `structure`", 'research_gateway/core/sdmx.py',
               '"structures": S.lookup(STRUCTURE), "dataSets"',
               '"structures": S.any_(), "dataSets"',
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_sdmx_every_place_a_message_states_its_structure_is_read',),
               ('tests.test_alternatives.OtherFormsOfTheSameShape.test_sdmx_data_sets_are_read_beside_a_wrapper_that_cannot_be_read',)),
        Mutant('R10-loader-typed-issns-chosen-before-the-plain-list-is-read', 'the Crossref journals loader never decodes the plain ISSN list: it is read only when the typed one is empty', 'research_gateway/harvest/registries.py',
               '"ISSN": S.own(S.text()),',
               '"ISSN": S.any_(),',
               ('tests.test_alternatives.LoaderAlternatives.test_crossref_journals_read_both_issn_lists_before_choosing_one',),
               ('tests.test_alternatives.LoaderAlternatives.test_datacite_repositories_read_the_symbol_and_the_id_before_choosing',)),
        Mutant('R10-loader-datacite-id-read-only-without-a-symbol', "the DataCite repositories loader never decodes a repository's id: it is read only when it has no symbol", 'research_gateway/harvest/registries.py',
               'REPOSITORY = S.obj({"id": S.text(),',
               'REPOSITORY = S.obj({"id": S.any_(),',
               ('tests.test_alternatives.LoaderAlternatives.test_datacite_repositories_read_the_symbol_and_the_id_before_choosing',),
               ('tests.test_alternatives.LoaderAlternatives.test_crossref_journals_read_both_issn_lists_before_choosing_one',)),
        Mutant('R9-europepmc-flag-not-text-is-no', 'a Europe PMC flag that is a list, a number or false is read as N', 'research_gateway/adapters/europepmc.py',
               '"hasTextMinedTerms": S.text(), "inEPMC": S.text(), "isOpenAccess": S.text()}',
               '"hasTextMinedTerms": S.any_(), "inEPMC": S.any_(), "isOpenAccess": S.any_()}',
               ('tests.test_typed_fields.EuropePmcFlags.test_a_flag_that_is_not_text_is_unreadable_not_no', 'tests.test_invariants.Corruptions.test_b_an_unreadable_container_is_never_empty__europepmc_find__populated'),
               ('tests.test_typed_fields.EuropePmcFlags.test_control_y_and_n_and_nothing_are_read',)),
        Mutant('R9-europepmc-second-flag-not-read-when-the-first-says-yes', "`has_full_text`'s second flag is never decoded: it is read only when the first says no", 'research_gateway/adapters/europepmc.py',
               '"hasTextMinedTerms": S.text(), "inEPMC": S.text(),',
               '"hasTextMinedTerms": S.text(), "inEPMC": S.any_(),',
               ('tests.test_typed_fields.EuropePmcFlags.test_one_flag_that_says_yes_does_not_hide_another_that_is_unreadable',),
               ('tests.test_typed_fields.EuropePmcFlags.test_control_y_and_n_and_nothing_are_read',)),
        Mutant('R9-doaj-ref-object-without-url-is-no-link', "a DOAJ journal's ref that is an object with no url is a link the journal leaves out", 'research_gateway/adapters/doaj.py',
               '"ref": S.table(S.oneof(S.obj({"url": S.required(S.text())}), S.text()))',
               '"ref": S.table(S.oneof(S.obj({"url": S.text()}), S.text()))',
               ('tests.test_typed_fields.DoajJournalRef.test_a_ref_that_is_the_wrong_kind_is_unreadable_not_a_journal_without_it', 'tests.test_invariants.Corruptions.test_b_an_unreadable_container_is_never_empty__doaj_resolve__a_journal_by_its_ISSN___populated'),
               ('tests.test_typed_fields.DoajJournalRef.test_control_a_ref_that_is_text_or_an_object_with_a_url_or_nothing_is_read',)),
        Mutant('R9-fred-notes-read-by-truth', "FRED's notes that are false, 0, [] or {} say the series is not restricted", 'research_gateway/adapters/fred.py',
               '"frequency": S.any_(), "notes": S.text()})))})',
               '"frequency": S.any_(), "notes": S.any_()})))})',
               ('tests.test_typed_fields.RestrictionsAreReadAsWhatTheyAre.test_fred_notes_that_are_not_text_make_the_series_unreadable',),
               ('tests.test_typed_fields.RestrictionsAreReadAsWhatTheyAre.test_fred_control_notes_that_say_restricted_or_nothing',)),
        Mutant('R9-dataverse-restricted-read-by-truth', 'a Dataverse file whose `restricted` is 0, "" or [] is not restricted', 'research_gateway/adapters/harvard_dataverse.py',
               'FILE = S.obj({"label": S.text(), "restricted": S.flag(),',
               'FILE = S.obj({"label": S.text(), "restricted": S.any_(),',
               ('tests.test_typed_fields.RestrictionsAreReadAsWhatTheyAre.test_a_dataverse_files_restricted_flag_is_a_flag',),
               ('tests.test_typed_fields.RestrictionsAreReadAsWhatTheyAre.test_a_flag_is_read_as_one', 'tests.test_member_decoding.DataverseDownloadMembership.test_an_unreadable_member_does_not_block_a_readable_file')),
        Mutant('R9-dataverse-identifier-read-by-truth', 'a Dataverse dataset whose `identifier` is false, 0 or [] is a dataset with no DOI', 'research_gateway/adapters/harvard_dataverse.py',
               '_DATASET = {"id": S.maybe_key(), "identifier": S.text(),',
               '_DATASET = {"id": S.maybe_key(), "identifier": S.any_(),',
               ('tests.test_typed_fields.RestrictionsAreReadAsWhatTheyAre.test_a_dataverse_dataset_whose_identifier_is_not_text_is_unreadable_not_a_dataset_with_no_doi',),
               ('tests.test_member_decoding.DataverseDownloadMembership.test_an_unreadable_member_does_not_block_a_readable_file',)),
        Mutant('R9-census-label-read-by-truth', 'a Census variable whose label is false, 0 or [] is a variable with none', 'research_gateway/adapters/census.py',
               'S.obj({"label": S.text(), "predicateOnly": S.flag()})',
               'S.obj({"label": S.any_(), "predicateOnly": S.flag()})',
               ('tests.test_typed_fields.CatalogueEntries.test_census_a_variable_whose_label_or_flag_is_the_wrong_kind_makes_the_catalogue_unreadable',),
               ('tests.test_typed_fields.CatalogueEntries.test_census_control_a_predicate_variable_and_a_variable_with_no_label',)),
        Mutant('R9-census-predicate-flag-read-by-truth', 'a Census variable whose predicateOnly is 0, "" or "false" is read by its truth', 'research_gateway/adapters/census.py',
               'S.obj({"label": S.text(), "predicateOnly": S.flag()})',
               'S.obj({"label": S.text(), "predicateOnly": S.any_()})',
               ('tests.test_typed_fields.CatalogueEntries.test_census_a_variable_whose_label_or_flag_is_the_wrong_kind_makes_the_catalogue_unreadable',),
               ('tests.test_typed_fields.CatalogueEntries.test_census_control_a_predicate_variable_and_a_variable_with_no_label',)),
        Mutant('R9-sdmx-id-or-name-read-by-truth', 'an SDMX entry whose id is false or [] is known by its name', 'research_gateway/core/sdmx.py',
               'DIM_VALUE = S.obj({"id": S.text(), "name": S.text()})',
               'DIM_VALUE = S.obj({"id": S.any_(), "name": S.text()})',
               ('tests.test_typed_fields.SdmxEntries.test_an_id_or_a_name_that_is_not_text_is_unreadable_not_a_missing_one',),
               ('tests.test_typed_fields.SdmxEntries.test_control_the_id_wins_and_the_name_stands_in', 'tests.test_present_means_typed.Structures.test_dimensions_and_observations_that_are_there_and_the_wrong_kind_are_unreadable')),
        Mutant('R9-agency-of-any-kind-is-a-name', "doi.org's RA that is false, 0, [] or a number is read as an agency of that spelling", 'research_gateway/core/identity.py',
               'RA_ROWS = S.members(S.obj({"RA": S.text()}))',
               'RA_ROWS = S.members(S.obj({"RA": S.any_()}))',
               ('tests.test_typed_fields.RegistrationAgency.test_an_agency_that_is_not_text_is_neither_one_nor_remembered',),
               ('tests.test_typed_fields.RegistrationAgency.test_control_text_is_the_agency_and_no_agency_is_unknown', 'tests.test_payload_shapes.AdapterBoundary.test_a_garbled_registration_agency_answer_is_not_remembered')),
        Mutant('R9-metadata-container-crashes-the-page', 'a total read through `meta.total` loses the members beside it when `meta` is not an object', 'research_gateway/adapters/datacite.py',
               ('"meta.total": S.deep(("meta", "total"), S.whole())})', 'count = total(j["meta.total"], (page - 1) * size + len(data))'),
               ('"meta": S.obj({"total": S.soft(S.whole())})})', 'count = total(j["meta"]["total"], (page - 1) * size + len(data))'),
               ('tests.test_invariants.Corruptions.test_c_readable_peers_survive__datacite_find__a_full_page', 'tests.test_invariants.Corruptions.test_c_readable_peers_survive__datacite_find__the_page_that_reaches_the_total'),
               ('tests.test_provider_pagination.DataCiteDois.test_continues', 'tests.test_provider_pagination.DataCiteDois.test_ends')),
        Mutant('R9-browse-repeats-a-dimension', 'a dimension that a structure lists twice is listed twice', 'research_gateway/core/sdmx.py',
               'if el["@id"] and all(el["@id"] != d for _, d in dims):',
               'if el["@id"]:',
               ('tests.test_station_contract.CatalogDiscovery.test_a_dimension_listed_twice_in_one_structure_stands_once_and_the_order_is_the_position',),
               ('tests.test_station_contract.CatalogDiscovery.test_ecb_dataflows_then_dimensions_in_key_order',)),
        Mutant('R9-browse-takes-a-structure-by-its-id-alone', "a structure of the same id from another agency or version is the flow's structure", 'research_gateway/core/sdmx.py',
               'for k in ("id", "agencyID", "version") if structure_.get(k) is not None)',
               'for k in ("id",) if structure_.get(k) is not None)',
               ('tests.test_station_contract.CatalogDiscovery.test_a_structure_other_than_the_one_the_flow_names_is_no_structure_of_the_flow',),
               ('tests.test_station_contract.CatalogDiscovery.test_a_reference_that_states_only_an_id_matches_the_structure_of_that_id', 'tests.test_station_contract.CatalogDiscovery.test_ecb_dataflows_then_dimensions_in_key_order')),
        Mutant('R10-a-flow-of-another-agency-is-the-flow-asked-for', 'a dataflow another agency maintains answers a browse of the requested id', 'research_gateway/core/sdmx.py',
               '        if f["id"] == wanted and f["agency"] in (None, agency):',
               '        if f["id"] == wanted:',
               ('tests.test_flow_binding.SelectionOfTheFlow.test_a_flow_another_agency_maintains_is_not_the_flow_asked_for',),
               ('tests.test_flow_binding.SelectionOfTheFlow.test_the_flow_asked_for_is_the_one_found_by_its_id',)),
        Mutant('R10-ambiguous-structure-is-read-as-the-first', 'a structure reference that two structures with different dimensions answer to is read as the first', 'research_gateway/core/sdmx.py',
               '    if len(answers) > 1:\n        raise PayloadError(f"an SDMX answer in which the data structure {structure_.get(\'id\')!r} names {len(found)} structures with different dimensions: nothing says which one is meant")\n    return list(next(iter(answers))) if answers else []',
               '    return list(_dimension_ids(found[0])) if found else []',
               ('tests.test_flow_binding.SelectionOfTheFlow.test_a_reference_that_more_than_one_structure_answers_to_is_ambiguous_unless_they_agree', 'tests.test_flow_binding.BrowseOfTheFlowAskedFor.test_an_ambiguous_flow_or_structure_is_an_unreadable_answer_and_not_the_first_of_them'),
               ('tests.test_station_contract.CatalogDiscovery.test_ecb_dataflows_then_dimensions_in_key_order', 'tests.test_station_contract.CatalogDiscovery.test_a_reference_that_states_only_an_id_matches_the_structure_of_that_id')),
        Mutant('R10-a-flows-structure-is-any-ref-under-it', "a dataflow's structure is the first `Ref` anywhere under the flow, not its own Structure child's", 'research_gateway/core/sdmx.py',
               ('    refs = [r["@*"] for st in structures for r in st["Ref"] if r["@*"].get("id")]', '"Structure": S.own(S.obj({"Ref": S.own(S.obj({"@*": ATTRIBUTES})), "URN": S.own(S.obj({"#": S.text()}))}))},\n                     rule=_reference)'),
               ('    refs = [r["@*"] for r in rec["**Ref"] if r["@*"].get("id")]', '"**Ref": S.own(S.obj({"@*": ATTRIBUTES})), "Structure": S.own(S.obj({"URN": S.own(S.obj({"#": S.text()}))}))},\n                     rule=_reference)'),
               ('tests.test_flow_binding.SelectionOfTheFlow.test_only_the_structure_child_of_the_flow_names_its_structure',),
               ('tests.test_flow_binding.SelectionOfTheFlow.test_the_flow_asked_for_is_the_one_found_by_its_id',)),
        Mutant('R10-bis-browse-takes-the-first-flow', 'BIS answers a browse with the first dataflow of the message, whichever was asked for', 'research_gateway/adapters/bis.py',
               '    flow = sdmx.dataflow_named(SOURCE_ID, sdmx.flows(SOURCE_ID, resp.text), within, AGENCY)',
               '    flow = sdmx.dataflow_named(SOURCE_ID, sdmx.flows(SOURCE_ID, resp.text), (sdmx.flows(SOURCE_ID, resp.text) or [{"id": within}])[0]["id"], AGENCY)',
               ('tests.test_oracle.FlowBinding.test_the_answer_is_about_the_flow_asked_for_wherever_it_stands', 'tests.test_oracle.FlowBinding.test_a_flow_that_cannot_be_bound_yields_no_entry_and_no_template', 'tests.test_flow_binding.BrowseOfTheFlowAskedFor.test_the_entry_is_the_flows_own_in_every_position_for_both_providers'),
               ('tests.test_station_contract.CatalogDiscovery.test_a_browse_names_the_dimensions_of_the_flows_own_structure_and_never_merges_the_structures_of_a_message',)),
        Mutant('R10-ecb-browse-takes-the-first-flow', 'ECB answers a browse with the first dataflow of the message, whichever was asked for', 'research_gateway/adapters/ecb.py',
               '    flow = sdmx.dataflow_named(SOURCE_ID, sdmx.flows(SOURCE_ID, resp.text), within, AGENCY)',
               '    flow = sdmx.dataflow_named(SOURCE_ID, sdmx.flows(SOURCE_ID, resp.text), (sdmx.flows(SOURCE_ID, resp.text) or [{"id": within}])[0]["id"], AGENCY)',
               ('tests.test_oracle.FlowBinding.test_the_answer_is_about_the_flow_asked_for_wherever_it_stands', 'tests.test_oracle.FlowBinding.test_a_flow_that_cannot_be_bound_yields_no_entry_and_no_template', 'tests.test_flow_binding.BrowseOfTheFlowAskedFor.test_the_entry_is_the_flows_own_in_every_position_for_both_providers'),
               ('tests.test_station_contract.CatalogDiscovery.test_a_browse_names_the_dimensions_of_the_flows_own_structure_and_never_merges_the_structures_of_a_message',)),
        Mutant('R9-star-import-in-an-adapter', 'an adapter imports `*` from the client, so the door check cannot see what it uses', 'research_gateway/adapters/opencitations.py',
               'from .base import OMIT, Client, check, decode, first_member, members',
               'from .base import *',
               ('tests.test_member_isolation.Imports.test_every_provider_data_module_imports_only_what_the_inventory_admits',),
               ('tests.test_member_isolation.Imports.test_provider_data_modules_are_exactly_the_ones_that_read_an_answer', 'tests.test_member_isolation.Imports.test_every_other_form_an_import_can_take_is_refused_or_analysed')),
        Mutant('R9-adapter-imports-a-name-the-client-does-not-export', 'an adapter imports a helper of the client that is not in its __all__', 'research_gateway/adapters/opencitations.py',
               'from .base import OMIT, Client, check, decode, first_member, members',
               'from .base import OMIT, Client, check, decode, first_member, members, header_map',
               ('tests.test_member_isolation.Imports.test_every_provider_data_module_imports_only_what_the_inventory_admits',),
               ('tests.test_member_isolation.Imports.test_provider_data_modules_are_exactly_the_ones_that_read_an_answer', 'tests.test_member_isolation.Imports.test_every_other_form_an_import_can_take_is_refused_or_analysed')),
        Mutant('R9-adapter-reaches-a-parser-through-an-admitted-module', "an adapter reads a provider's body with the parser an admitted package module imports (`cache.json`)", 'research_gateway/adapters/opencitations.py',
               '    rows = decode(SOURCE_ID, SCHEMAS[f"enrich:{what}"], resp.json)\n',
               '    from ..core import cache as provider_helpers\n    rows = decode(SOURCE_ID, SCHEMAS[f"enrich:{what}"], [row for row in provider_helpers.json.loads(resp.body) if row.get(key)])\n',
               ('tests.test_member_isolation.Imports.test_every_provider_data_module_imports_only_what_the_inventory_admits',),
               ('tests.test_member_isolation.Imports.test_provider_data_modules_are_exactly_the_ones_that_read_an_answer', 'tests.test_member_isolation.Imports.test_the_client_has_no_parser_to_re_export_and_exports_no_module')),
    ]
