"""The task-2b gateway mutant inventory run by tools/gen2_gateway_mutations.py.

Each mutant removes or weakens exactly ONE guard of the gateway repairs (the edit `old`
→ `new` must occur exactly once in `target`, a path under gateway/). `killers` must fail
under it; `controls` must pass under it — tests that take the accepted path through the
same code, so a kill does not rest on that path being broken. `db` marks a mutant whose
killers need the scratch database. Test ids are unittest names from gateway/.

Not in the inventory, and why: the schema's immutability trigger (DDL applied to a shared
scratch database — tested directly by DurableCorrelation.test_correlation_is_immutable_
once_written, not mutated); the front door's admit() before submit()/handle() (both bind
again: removing one layer is an equivalent mutant); Grants.mint's `grantor.bound` clause
(a grant's principal is never a grantor: equivalent); crossref._record's own refusal of a work
with neither DOI nor URL (2b-repair A4: members() and the router both drop the `url:None` it
would build — a second and third layer that make removing the first equivalent); the
migration's `restriction_inputs = true` (2b-repair-4 F2: a migration that marks nothing fails its
own completion check in every test that converts a row, so no accepted path is left to pair a
control with); each of its two `NOT restriction_inputs` (the pass's list of rows, and the batch's
re-check under lock of a row a current writer converted meanwhile: each backs the other, so
removing one is equivalent without concurrency; that a rerun converts nothing and a current
writer's row is never rewritten is test_the_migration_runs_once_and_says_when_it_is_done's).
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Mutant:
    mid: str
    description: str
    target: str
    old: str
    new: str
    killers: tuple[str, ...]
    controls: tuple[str, ...]
    db: bool = False


SC = "tests.test_secrets_contract."
PS, LO = "tests.test_payload_shapes.AdapterBoundary.", "tests.test_lane_outcomes."
CO, SP, PV = "tests.test_correlation.", "tests.test_server_policy.", "tests.test_provenance."
SECRETS, ROUTER, BASE, APP = "research_gateway/core/secrets.py", "research_gateway/core/router.py", "research_gateway/adapters/base.py", "research_gateway/app.py"
PRINC, HTTP, MCP, STDIO = "research_gateway/core/principals.py", "research_gateway/api/http.py", "research_gateway/mcp/homelab_adapter.py", "research_gateway/clients/mcp_stdio.py"
LIC = "research_gateway/core/licenses.py"
CACHE, MIGRATE = "research_gateway/core/cache.py", "research_gateway/registry/migrate.py"

MUTANTS: list[Mutant] = [
    # ---- item 6: secrets outcomes (DEPLOYMENT-CONTRACT §3.4) ---------------------------------------------
    Mutant("S-home-fallback", "an unset token-file variable falls back to ~/.vault-token", SECRETS,
           'self.token_file = token_file or env.get(TOKEN_FILE_VAR) or ""',
           'self.token_file = token_file or env.get(TOKEN_FILE_VAR) or os.path.expanduser("~/.vault-token")',
           (SC + "F1NoHomeFallback.test_refuses_to_start_and_never_opens_the_home_token",),
           (SC + "F1NoHomeFallback.test_control_an_explicit_token_file_starts_the_service",)),
    Mutant("S-no-address", "a vault backend without an address is accepted", SECRETS,
           "        if not self.addr:\n            raise SecretsConfigError", "        if False:\n            raise SecretsConfigError",
           ("tests.test_core_foundations.Secrets.test_vault_backend_without_address_refuses",),
           (SC + "F4GenuinelyAbsent.test_absent_is_absent_and_does_not_alarm",)),
    Mutant("S-unreadable-token-starts", "an unreadable token file at startup is accepted", SECRETS,
           "        if problem:\n            raise SecretsConfigError", "        if False:\n            raise SecretsConfigError",
           (SC + "F2ExplicitFileUnreadable.test_a_missing_path_at_startup_is_refused",),
           (SC + "F1NoHomeFallback.test_control_an_explicit_token_file_starts_the_service",)),
    Mutant("S-failing-reads-absent", "a failed read is returned as absent", SECRETS,
           '        if kind == "failing":\n            return payload\n        if kind == "absent":',
           '        if kind == "failing":\n            return SecretRead(ABSENT)\n        if kind == "absent":',
           (SC + "F3TransportAndStatus.test_each_failure_is_failing_and_never_absent", SC + "F8OutageReplay.test_the_outage_reads_as_an_outage",
            SC + "F5OutcomeSurvivesTheHttpBoundary.test_per_lane_outcome_over_http"),
           (SC + "F4GenuinelyAbsent.test_absent_is_absent_and_does_not_alarm", SC + "F5OutcomeSurvivesTheHttpBoundary.test_control_a_readable_secret_answers")),
    Mutant("S-missing-mount-absent", "a 404 for a mount that does not exist reads as absent", SECRETS,
           "        if errors == []:\n            return \"absent\", None", "        if True:\n            return \"absent\", None",
           (SC + "F4GenuinelyAbsent.test_control_the_same_path_under_a_missing_mount_is_failing",
            SC + "F3TransportAndStatus.test_each_failure_is_failing_and_never_absent"),
           (SC + "F4GenuinelyAbsent.test_absent_is_absent_and_does_not_alarm",)),
    Mutant("S-success-status-unchecked", "a success status other than 200 is read as the secret (A7)", SECRETS,
           "        if status != 200:", "        if False:",
           (SC + "F3TransportAndStatus.test_a_valid_body_under_another_success_status_is_failing",),
           (SC + "F3TransportAndStatus.test_control_the_same_body_under_200_is_the_secret",)),
    Mutant("S-follows-redirects", "the vault opener follows redirects (the token goes elsewhere)", SECRETS,
           "    _opener = urllib.request.build_opener(_Opener)", "    _opener = urllib.request.build_opener()",
           (SC + "F7RedirectsRefused.test_no_redirect_is_followed",),
           (SC + "F4GenuinelyAbsent.test_absent_is_absent_and_does_not_alarm",)),
    Mutant("S-cache-launders", "a cached failure replays as absent", SECRETS,
           "            self._cache[vault_name] = (self._clock() + ttl, kind, payload)",
           '            self._cache[vault_name] = (self._clock() + ttl, "absent" if kind == "failing" else kind, payload)',
           (SC + "F6CacheDoesNotLaunderAFailure.test_failure_replay_expiry_and_recovery",),
           (SC + "F4GenuinelyAbsent.test_absent_is_absent_and_does_not_alarm",)),
    Mutant("S-stale-success", "a cached success outlives its TTL (a failed re-read is papered over)", SECRETS,
           "        if hit and hit[0] > now:", '        if hit and (hit[0] > now or hit[1] != "failing"):',
           (SC + "F6CacheDoesNotLaunderAFailure.test_failure_replay_expiry_and_recovery", SC + "F8OutageReplay.test_the_outage_reads_as_an_outage",
            SC + "F4GenuinelyAbsent.test_absent_is_absent_and_does_not_alarm"),   # a removed secret, re-read after its TTL, is absent
           (SC + "F5OutcomeSurvivesTheHttpBoundary.test_control_a_readable_secret_answers",)),
    Mutant("S-no-transition-alert", "a transition into failing does not alert", SECRETS,
           "            alert = self._settle(before)\n        self._notify(alert)\n\n    def _settle",
           "            alert = self._settle(before)\n        self._notify(False)\n\n    def _settle",
           (SC + "F3TransportAndStatus.test_the_capability_fact_is_dated_names_its_lanes_and_alerts_on_transition",),
           (SC + "F4GenuinelyAbsent.test_absent_is_absent_and_does_not_alarm",)),
    Mutant("S-no-status-line", "operator status carries no failing line", SECRETS,
           '        if f["state"] != "failing":\n            return None', '        if True:\n            return None',
           (SC + "F8OutageReplay.test_the_outage_reads_as_an_outage",),
           (SC + "F3TransportAndStatus.test_the_capability_fact_is_dated_names_its_lanes_and_alerts_on_transition",)),
    # ---- 2b-repair-3 R2: each change of the fact is its next revision; an answer carries the latest ------------
    Mutant("S-revision-uncounted", "a change of the capability fact is not a new revision", SECRETS,
           "        if self._content() != before:\n            self.revision += 1", "        if False:\n            self.revision += 1",
           (SC + "FactRevisions.test_each_change_is_the_next_revision_and_a_repeat_is_not",
            "tests.test_engine_fixtures.EngineFixtures.test_data_secrets_outage_recurs"),
           (SC + "F3TransportAndStatus.test_the_capability_fact_is_dated_names_its_lanes_and_alerts_on_transition",)),
    Mutant("S-revision-every-read", "a fresh read that changes nothing is a new revision", SECRETS,
           "        if self._content() != before:\n            self.revision += 1", "        if True:\n            self.revision += 1",
           (SC + "FactRevisions.test_each_change_is_the_next_revision_and_a_repeat_is_not",
            "tests.test_engine_fixtures.EngineFixtures.test_data_secrets_outage_two_invocations"),
           (SC + "F3TransportAndStatus.test_the_capability_fact_is_dated_names_its_lanes_and_alerts_on_transition",)),
    Mutant("R-fact-last-lane-wins", "an answer carries the fact of the lane collected last, not the latest revision", ROUTER,
           '        if held is None or fact.get("revision", 0) >= held.get("revision", 0):', "        if True:",
           (SC + "FactRevisions.test_an_answer_keeps_the_latest_snapshot_it_met",),
           ("tests.test_engine_fixtures.EngineFixtures.test_data_secrets_failing",)),
    Mutant("S-lane-generic", "a lane whose secret read failed is a generic unreadable lane", ROUTER,
           "    if isinstance(e, SecretsBackendFailing):\n        _secrets_failing(entry, facts, sid, e)\n        return e.fact\n",
           "",
           (SC + "F5OutcomeSurvivesTheHttpBoundary.test_per_lane_outcome_over_http",),
           (LO + "LaneOutcomes.test_each_refusal_names_its_error_class",)),
    Mutant("S-startup-token-read", "a failed token read at startup is taken for 'no tokens'", APP,
           "        if read.state == FAILING:\n            raise SecretsConfigError", "        if False:\n            raise SecretsConfigError",
           (SC + "F2ExplicitFileUnreadable.test_a_token_read_that_fails_at_startup_is_refused_as_failing",),
           (SC + "F1NoHomeFallback.test_control_an_explicit_token_file_starts_the_service",)),
    # ---- item 3: response shape at the adapter boundary --------------------------------------------------
    Mutant("P-json-lenient", "unparseable JSON reads as None", BASE,
           '            raise PayloadError(f"unparseable JSON (HTTP {self.status}, {len(self.body)} bytes)") from None',
           "            return None",
           (PS + "test_the_json_reader_refuses_what_it_cannot_read", PS + "test_a_garbled_registration_agency_answer_is_not_remembered"),
           (PS + "test_control_the_apis_own_empty_answer_stays_empty",)),
    Mutant("P-empty-lenient", "an empty body reads as None", BASE,
           '            raise PayloadError(f"empty body (HTTP {self.status})")', "            return None",
           (PS + "test_the_json_reader_refuses_what_it_cannot_read",), (PS + "test_control_the_apis_own_empty_answer_stays_empty",)),
    Mutant("P-need-lenient", "a missing result container reads as empty", BASE,
           '            raise PayloadError(f"{source_id}: the answer has no {\'.\'.join(path[:i + 1])}")', "            return []",
           (PS + "test_an_unreadable_success_is_never_an_empty_answer",), (PS + "test_control_the_apis_own_empty_answer_stays_empty",)),
    Mutant("P-search-404-empty", "crossref's search 404 reads as no results", "research_gateway/adapters/crossref.py",
           '    resp = client.get(SOURCE_ID, "find", f"{BASE}/works", params=params, query=query)\n    check(SOURCE_ID, resp, allow_404=False)',
           '    resp = client.get(SOURCE_ID, "find", f"{BASE}/works", params=params, query=query)\n    if not check(SOURCE_ID, resp):\n        return {"records": []}',
           (PS + "test_a_search_endpoints_404_is_an_outage_not_no_results",), (PS + "test_control_the_apis_own_empty_answer_stays_empty",)),
    Mutant("P-sdmx-lenient", "unparseable SDMX-ML reads as an empty message", "research_gateway/core/sdmx.py",
           '        raise PayloadError(f"unparseable SDMX-ML ({e})") from None', '        return ET.Element("StructureSpecificData")',
           ("tests.test_adapters_statistical.BisEcb.test_bis_reads_sdmx_ml",), (PS + "test_control_the_apis_own_empty_answer_stays_empty",)),
    Mutant("P-partial-complete", "a set that lost records is called complete", ROUTER,
           '    entry["completeness"] = "partial" if dropped else "complete"', '    entry["completeness"] = "complete"',
           (LO + "LaneOutcomes.test_dropped_records_make_a_partial_lower_bound",),
           (LO + "LaneOutcomes.test_control_all_readable_records_are_complete",)),
    Mutant("P-unreadable-records-empty", "a lane whose every record was unreadable is searched_empty", ROUTER,
           "    if dropped and not count:", "    if False:",
           (LO + "LaneOutcomes.test_only_unreadable_records_observe_nothing",), (LO + "LaneOutcomes.test_control_a_readable_empty_answer_is_searched_empty",)),
    Mutant("P-fact-counted", "a fact-only answer gets a count of 0", ROUTER,
           '        entry["error_class"] = ERR_UNCONFIGURED if entry["coverage"] == COVERAGE_AUTH else ERR_OUTAGE\n        return\n',
           '        entry["error_class"] = ERR_UNCONFIGURED if entry["coverage"] == COVERAGE_AUTH else ERR_OUTAGE\n',
           (LO + "LaneOutcomes.test_a_fact_only_answer_is_degraded_not_empty",), (LO + "LaneOutcomes.test_control_a_readable_empty_answer_is_searched_empty",)),
    Mutant("P-partial-exhausted", "a partial lane is marked exhausted", ROUTER,
           '    elif entry["coverage"] in (COVERAGE_OK, COVERAGE_EMPTY) and entry["completeness"] == "complete":',
           '    elif entry["coverage"] in (COVERAGE_OK, COVERAGE_EMPTY):',
           (LO + "LaneOutcomes.test_a_partial_lane_is_never_exhausted",), (LO + "LaneOutcomes.test_control_a_readable_empty_answer_is_searched_empty",)),
    Mutant("P-cursor-lost", "a lane does not echo the cursor it was asked with", ROUTER,
           '                   "cursor": (payload.get("cursors") or {}).get(lane.source_id)}', '                   "cursor": None}',
           (LO + "LaneOutcomes.test_a_failed_continuation_page_keeps_its_cursor",), (LO + "LaneOutcomes.test_control_all_readable_records_are_complete",)),
    Mutant("P-degraded-cached", "an answer with a degraded lane is cached", ROUTER,
           '            if rt == "find" and all(lane.get("completeness") == "complete"', '            if rt == "find" and True or all(lane.get("completeness") == "complete"',
           (LO + "DegradedAnswersAreNotReplayed.test_a_degraded_answer_is_asked_again", LO + "DegradedAnswersAreNotReplayed.test_a_partial_answer_is_asked_again"),
           (LO + "DegradedAnswersAreNotReplayed.test_control_a_complete_answer_is_served_from_cache",)),
    Mutant("P-resolve-fact-not-found", "a keyless resolve's fact is read as a record", ROUTER,
           '            if isinstance(rec, dict) and rec.get("capability_fact") and not rec.get("identity"):', "            if False:",
           (LO + "LaneOutcomes.test_a_resolve_capability_fact_is_not_not_found",), (LO + "LaneOutcomes.test_control_a_readable_empty_answer_is_searched_empty",)),
    Mutant("P-retrieved-missing", "a counted lane does not name what it counted", ROUTER,
           '                          else [str(r["identity"]) for r in got])', "                          else [])",
           (LO + "LaneOutcomes.test_dropped_records_make_a_partial_lower_bound", LO + "LaneOutcomes.test_control_all_readable_records_are_complete"),
           (LO + "LaneOutcomes.test_control_a_readable_empty_answer_is_searched_empty",)),
    # 2b-repair A4: provider members, each decoded alone, and every candidate names something
    Mutant("P-members-not-isolated", "one unreadable member discards the members read beside it", BASE,
           "        except MEMBER_ERRORS:\n            rec = None", "        except ZeroDivisionError:\n            rec = None",
           (LO + "RealAdapterMembers.test_a_later_bad_member_keeps_the_earlier_as_a_partial_lower_bound", LO + "RealAdapterMembers.test_each_member_is_decoded_alone"),
           (LO + "RealAdapterMembers.test_control_readable_members_are_complete_and_cached",)),
    Mutant("P-member-identity-unchecked", "a decoded member naming nothing (url:None) is kept by the adapter helper", BASE,
           '        out.append(rec if isinstance(rec, dict) and meaningful(rec.get("identity")) else None)',
           '        out.append(rec if isinstance(rec, dict) and rec.get("identity") else None)',
           (LO + "RealAdapterMembers.test_each_member_is_decoded_alone",), (LO + "RealAdapterMembers.test_control_readable_members_are_complete_and_cached",)),
    Mutant("P-router-identity-unchecked", "the router counts a record whose identity names nothing", ROUTER,
           '    good = [r for r in (items or []) if isinstance(r, dict) and ident.meaningful(r.get("identity")) and r.get("kind")]',
           '    good = [r for r in (items or []) if isinstance(r, dict) and r.get("identity") and r.get("kind")]',
           (LO + "LaneOutcomes.test_a_fabricated_identity_is_a_dropped_record",), (LO + "LaneOutcomes.test_control_all_readable_records_are_complete",)),
    # ---- items 1-2: invocation/attempt and complete request identity -------------------------------------
    Mutant("C-v1-drops-invocation", "the /v1 door drops the invocation headers", HTTP,
           '                 "topic": (self.headers.get("X-Research-Topic") or "")[:64] or None, **correlation}',
           '                 "topic": (self.headers.get("X-Research-Topic") or "")[:64] or None}',
           (CO + "BothDoorsCarryTheInvocation.test_the_v1_door_echoes_the_callers_invocation_and_attempt",),
           (CO + "BothDoorsCarryTheInvocation.test_control_what_is_not_research_needs_no_correlation",)),
    Mutant("C-malformed-accepted", "a malformed invocation id is accepted", APP,
           "    if not INVOCATION_RE.fullmatch(inv):", "    if False:",
           (CO + "BothDoorsCarryTheInvocation.test_malformed_or_half_given_correlation_is_refused",),
           (CO + "BothDoorsCarryTheInvocation.test_the_v1_door_echoes_the_callers_invocation_and_attempt",)),
    Mutant("C-mcp-drops-invocation", "the MCP door drops the invocation", MCP,
           '        tr = {**trace, **({"batch_entry": entry} if entry is not None else {})}',
           '        tr = {"batch_entry": entry} if entry is not None else {}',
           (CO + "BothDoorsCarryTheInvocation.test_the_mcp_door_carries_it_into_every_tool_call_and_batch_entry",),
           (CO + "BothDoorsCarryTheInvocation.test_the_v1_door_echoes_the_callers_invocation_and_attempt",)),
    Mutant("C-batch-entry-lost", "MCP batch entries lose their index", MCP,
           '                    results.append({"tool": tool, "result": call(tool, (entry or {}).get("arguments") or {}, index)})',
           '                    results.append({"tool": tool, "result": call(tool, (entry or {}).get("arguments") or {}, None)})',
           (CO + "BothDoorsCarryTheInvocation.test_the_mcp_door_carries_it_into_every_tool_call_and_batch_entry",),
           (CO + "BothDoorsCarryTheInvocation.test_the_v1_door_echoes_the_callers_invocation_and_attempt",)),
    Mutant("C-no-db-captured", "an answer without a database claims a durable row", APP,
           '            obs["capture_loss"] = "no durable call log: this gateway runs without a database"\n            return obs',
           '            obs["captured"] = True\n            return obs',
           (CO + "BothDoorsCarryTheInvocation.test_the_v1_door_echoes_the_callers_invocation_and_attempt",),
           (CO + "BothDoorsCarryTheInvocation.test_the_mcp_door_carries_it_into_every_tool_call_and_batch_entry",)),
    # 2b-repair A5: the pair is required on every research request, polls bound and recorded under their caller
    Mutant("C-v1-correlation-optional", "a /v1 research request without correlation runs unattributed", HTTP,
           "        if not problem and research and not correlation:", "        if False:",
           (CO + "BothDoorsCarryTheInvocation.test_a_research_request_without_correlation_is_refused_on_every_door",
            SP + "Grants_.test_the_grant_carries_its_invocation"),
           (CO + "BothDoorsCarryTheInvocation.test_the_v1_door_echoes_the_callers_invocation_and_attempt",)),
    Mutant("C-mcp-correlation-optional", "an MCP research tool call without correlation runs unattributed", MCP,
           '        if not tr.get("invocation_id"):   # every research tool call is attributed (2b-repair A5)', "        if False:",
           (CO + "BothDoorsCarryTheInvocation.test_a_research_request_without_correlation_is_refused_on_every_door",),
           (CO + "BothDoorsCarryTheInvocation.test_the_mcp_door_carries_it_into_every_tool_call_and_batch_entry",)),
    Mutant("C-poll-uncorrelated", "a job poll without correlation is answered", HTTP,
           "            trace = self._trace(research=True)   # a poll is research: bound and recorded under its caller (A5)",
           "            trace = self._trace()",
           (CO + "BothDoorsCarryTheInvocation.test_a_research_request_without_correlation_is_refused_on_every_door",),
           ("tests.test_http_api.InlineGateway.test_bad_requests",)),
    Mutant("C-poll-unbound", "a grant's poll may name another invocation", APP,
           "        trace = bind_correlation(dict(trace or {}), principal)", "        trace = dict(trace or {})",
           (SP + "JobsAreTheirTopicsAlone.test_a_poll_naming_another_invocation_or_none_is_refused",),
           (SP + "JobsAreTheirTopicsAlone.test_control_its_own_topic_reads_its_job",), db=True),
    Mutant("C-poll-as-creator", "a poll's observation names the job's creator, not its caller", APP,
           '        obs = {"invocation_id": trace.get("invocation_id"), "attempt": trace.get("attempt"),\n'
           '               "request_identity": j.get("request_identity"), "served": "polled",',
           '        obs = {"invocation_id": j.get("invocation_id"), "attempt": j.get("attempt"),\n'
           '               "request_identity": j.get("request_identity"), "served": "polled",',
           (SP + "JobsAreTheirTopicsAlone.test_a_poll_is_bound_and_recorded_under_its_own_caller",),
           (SP + "JobsAreTheirTopicsAlone.test_control_its_own_topic_reads_its_job",), db=True),
    Mutant("C-poll-row-as-creator", "a poll's durable row is written under the job's creator", APP,
           '                    invocation_id=obs["invocation_id"], attempt=obs["attempt"], request_identity=j.get("request_identity")))',
           '                    invocation_id=j.get("invocation_id"), attempt=j.get("attempt"), request_identity=j.get("request_identity")))',
           (SP + "JobsAreTheirTopicsAlone.test_a_poll_is_bound_and_recorded_under_its_own_caller",),
           (SP + "JobsAreTheirTopicsAlone.test_control_its_own_topic_reads_its_job",), db=True),
    Mutant("C-download-observation-dropped", "the station client drops a download's observation header",
           "research_gateway/clients/http_client.py",
           '        return {"content": raw, "content_type": ctype, **raw_observation(observed)}', '        return {"content": raw, "content_type": ctype}',
           ("tests.test_http_api.InlineGateway.test_the_station_client_keeps_a_downloads_observation",
            "tests.test_http_api.InlineGateway.test_bytes_without_their_observation_say_so"),
           ("tests.test_http_api.InlineGateway.test_control_a_download_through_the_station_client_is_its_bytes",)),
    Mutant("C-subject-collapses", "a request key keeps only its query (kind and cursor collide)", STDIO,
           '    if not extra and base_key != "source":', '    if base_key != "source":',
           (CO + "RequestIdentity.test_the_design_reviews_probe_kind_and_cursor_no_longer_collide",),
           (CO + "RequestIdentity.test_control_spellings_of_one_request_share_its_identity",)),
    Mutant("C-identity-no-cursor", "the effective request drops its cursors", "research_gateway/core/request_identity.py",
           "                   cursors=dict(payload.get(\"cursors\") or {}),", "                   cursors={},",
           (CO + "RequestIdentity.test_the_design_reviews_probe_kind_and_cursor_no_longer_collide",),
           (CO + "RequestIdentity.test_control_spellings_of_one_request_share_its_identity",)),
    Mutant("C-identity-no-default", "the effective request leaves the default page size unapplied", "research_gateway/core/request_identity.py",
           '        out.update(query=payload.get("query") or "", kind=payload.get("kind"), limit=payload.get("limit") or DEFAULT_LIMIT,',
           '        out.update(query=payload.get("query") or "", kind=payload.get("kind"), limit=payload.get("limit"),',
           (CO + "RequestIdentity.test_control_spellings_of_one_request_share_its_identity",),
           (CO + "RequestIdentity.test_the_design_reviews_probe_kind_and_cursor_no_longer_collide",)),
    Mutant("C-activity-loss-silent", "a failed activity write is acknowledged as captured", STDIO,
           '        return {"captured": False, "loss": f"activity file not written ({why}); "',
           '        return {"captured": True, "loss": f"activity file not written ({why}); "',
           (CO + "StdioClient.test_a_failed_activity_write_is_acknowledged_and_announced_later", CO + "StdioClient.test_the_tool_result_carries_the_loss"),
           (CO + "StdioClient.test_the_gateway_line_is_the_transport_and_a_pending_answer_clears_nothing",)),
    Mutant("C-pending-clears", "a pending answer writes the clearing gateway line", STDIO,
           "    if not gateway_trouble and result is not None and not pending:", "    if not gateway_trouble and result is not None:",
           (CO + "StdioClient.test_the_gateway_line_is_the_transport_and_a_pending_answer_clears_nothing",),
           (CO + "StdioClient.test_a_failed_activity_write_is_acknowledged_and_announced_later",)),
    Mutant("C-attempt-constant", "every repeat of a request is attempt 1", STDIO,
           "        _ATTEMPTS[identity] = _ATTEMPTS.get(identity, 0) + 1", "        _ATTEMPTS[identity] = 1",
           (CO + "StdioClient.test_attempts_number_repeats_of_one_request",),
           (CO + "StdioClient.test_the_gateway_line_is_the_transport_and_a_pending_answer_clears_nothing",)),
    Mutant("C-job-unattributed", "a queued job does not keep its creator's invocation", "research_gateway/core/queue.py",
           "                     invocation_id, attempt, request_identity),", "                     None, None, request_identity),",
           (CO + "DurableCorrelation.test_a_queued_job_and_its_lane_calls_carry_the_creators_invocation",),
           (CO + "DurableCorrelation.test_a_lost_request_row_is_reported_not_implied",), db=True),
    Mutant("C-lane-rows-unattributed", "lane call rows do not carry the invocation", BASE,
           '        return {"invocation_id": self.invocation_id, "attempt": self.attempt, "request_identity": self.request_identity}',
           '        return {"invocation_id": None, "attempt": None, "request_identity": self.request_identity}',
           (CO + "DurableCorrelation.test_a_queued_job_and_its_lane_calls_carry_the_creators_invocation",),
           (CO + "DurableCorrelation.test_a_lost_request_row_is_reported_not_implied",), db=True),
    Mutant("C-waiter-unattributed", "a coalesced caller's row carries no invocation", APP,
           "                        invocation_id=invocation_id, attempt=attempt, request_identity=rid))",
           "                        invocation_id=None, attempt=None, request_identity=rid))",
           (CO + "DurableCorrelation.test_a_coalesced_caller_keeps_its_own_invocation",),
           (CO + "DurableCorrelation.test_a_queued_job_and_its_lane_calls_carry_the_creators_invocation",), db=True),
    Mutant("C-coalesced-as-dispatched", "a coalesced caller is told it dispatched", APP,
           '                  else "coalesced" if out.get("created") is False\n', "",
           (CO + "DurableCorrelation.test_a_coalesced_caller_keeps_its_own_invocation",),
           (CO + "DurableCorrelation.test_a_queued_job_and_its_lane_calls_carry_the_creators_invocation",), db=True),
    Mutant("C-row-loss-silent", "a lost request row is not reported", APP,
           '            obs["capture_loss"] = f"request row not written: {type(e).__name__}"[:200]', "            pass",
           (CO + "DurableCorrelation.test_a_lost_request_row_is_reported_not_implied",),
           (CO + "DurableCorrelation.test_a_queued_job_and_its_lane_calls_carry_the_creators_invocation",), db=True),
    # ---- item 4: server-side policy ------------------------------------------------------------------------
    Mutant("G-bind-noop", "a grant's policy is not applied", PRINC,
           "    if not principal.bound:\n        return payload\n    out = dict(payload)", "    return payload\n    out = dict(payload)",
           (SP + "Grants_.test_the_v1_door_binds_the_topic_policy", SP + "Grants_.test_the_mcp_door_binds_it_too"),
           (SP + "Grants_.test_control_an_unbound_client_is_unchanged",)),
    Mutant("G-conflict-overridden", "a conflicting argument is silently overridden", PRINC,
           '            raise PolicyError(f"policy-bound: {key} is set by the topic, not the caller")', "            pass",
           (SP + "Grants_.test_the_v1_door_binds_the_topic_policy",), (SP + "Grants_.test_control_an_unbound_client_is_unchanged",)),
    Mutant("G-invocation-free", "a grant-bearer may name another invocation", PRINC,
           '        raise PolicyError("policy-bound: the invocation is set by the grant, and the request must carry it")', "        pass",
           (SP + "Grants_.test_the_grant_carries_its_invocation",), (SP + "Grants_.test_control_an_unbound_client_is_unchanged",)),
    Mutant("G-invocation-optional", "a grant's request naming no invocation runs (2b-repair A5)", PRINC,
           '    if trace.get("invocation_id") != principal.invocation_id:',
           '    if trace.get("invocation_id") not in (None, principal.invocation_id):',
           (SP + "Grants_.test_in_process_a_grant_request_carries_the_pair_too",),
           (SP + "Grants_.test_control_the_grants_invocation_with_the_callers_attempt_runs",)),
    Mutant("G-attempt-defaulted", "a grant's request without an attempt runs (2b-repair A5)", PRINC,
           '    if not isinstance(trace.get("attempt"), int) or isinstance(trace.get("attempt"), bool) or trace["attempt"] < 1:',
           "    if False:",
           (SP + "Grants_.test_in_process_a_grant_request_carries_the_pair_too",),
           (SP + "Grants_.test_control_the_grants_invocation_with_the_callers_attempt_runs",)),
    Mutant("G-unsigned", "a grant's signature is not checked", PRINC,
           "        if not body or not sig or not hmac.compare_digest(sig, self._sign(body)):", "        if not body or not sig:",
           (SP + "Grants_.test_a_forged_altered_expired_or_foreign_grant_is_refused",), (SP + "Grants_.test_only_a_grantor_mints_and_a_grant_never_does",)),
    Mutant("G-never-expires", "an expired grant is accepted", PRINC,
           ' or claims["exp"] <= self._clock():', ":",
           (SP + "Grants_.test_a_forged_altered_expired_or_foreign_grant_is_refused",), (SP + "Grants_.test_only_a_grantor_mints_and_a_grant_never_does",)),
    Mutant("G-everyone-grantor", "every configured client may mint grants", APP,
           "                return Principal(name=name, grantor=name in self.settings.grantors)",
           "                return Principal(name=name, grantor=True)",
           (SP + "Grants_.test_only_a_grantor_mints_and_a_grant_never_does",), (SP + "Grants_.test_a_grant_request_states_its_posture",)),
    Mutant("G-mcp-unbound", "the MCP door runs under the grantor's bare name, unbound", HTTP,
           "            reply = homelab_adapter.rpc(self.server.gateway, client, body, trace=trace)",
           "            reply = homelab_adapter.rpc(self.server.gateway, client.name, body, trace=trace)",
           (SP + "Grants_.test_the_mcp_door_binds_it_too",), (SP + "Grants_.test_the_v1_door_binds_the_topic_policy",)),
    Mutant("G-posture-unchecked", "a job is readable under a looser posture of its topic", PRINC,
           '    return all(bool(payload.get(k)) == principal.policy[k] for k in ("commercial", "accept_per_item") if k in principal.policy)',
           "    return True",
           (SP + "JobsAreTheirTopicsAlone.test_polling_never_crosses_topics_or_postures",),
           (SP + "JobsAreTheirTopicsAlone.test_control_its_own_topic_reads_its_job",), db=True),
    # ---- item 5: licence, freshness, provenance -----------------------------------------------------------
    # 2b-repair A3: restrictions survive persistence; metadata licence is not content licence; availability is what was delivered
    Mutant("L-summary-drops-restrictions", "a stored member summary forgets the source's restrictions", "research_gateway/core/canonical.py",
           "    out.update({k: member[k] for k in MEMBER_RESTRICTIONS + INFERRED_RESTRICTIONS if isinstance(member.get(k), bool)})\n", "",
           (PV + "RestrictionsSurviveReload.test_a_prohibition_survives_a_fresh_process_reload",
            PV + "RestrictionsSurviveReload.test_third_party_terms_survive_a_fresh_process_reload"),
           (PV + "RestrictionsSurviveReload.test_control_an_unrestricted_cc0_record_reloads_permitted",), db=True),
    Mutant("L-legacy-prohibition-lost", "a row kept in record_sources loses its stored prohibition on reload", "research_gateway/core/cache.py",
           '             **({"redistributable": False} if redistribution == "prohibited" else {})}',
           "             }",
           (PV + "RestrictionsSurviveReload.test_a_legacy_row_keeps_its_stored_prohibition",),
           (PV + "RestrictionsSurviveReload.test_control_a_legacy_permitted_row_reloads_permitted",), db=True),
    Mutant("L-inputs-marker-unwritten", "the current writer's new row is not marked as carrying its inputs", "research_gateway/core/cache.py",
           "now(), true) ", "now(), false) ",
           (PV + "RestrictionsSurviveReload.test_control_a_row_written_with_its_inputs_is_derived_from_them_alone",),
           (PV + "RestrictionsSurviveReload.test_a_pre_repair_row_written_again_is_the_current_writers",), db=True),
    Mutant("L-rewritten-row-keeps-old-marker", "a row an earlier writer left, written again by the current writer, keeps its old marker",
           "research_gateway/core/cache.py", '"restriction_inputs = true",', '"restriction_inputs = gateway.records.restriction_inputs",',
           (PV + "RestrictionsSurviveReload.test_a_pre_repair_row_written_again_is_the_current_writers",),
           (PV + "RestrictionsSurviveReload.test_a_prohibition_survives_a_fresh_process_reload",), db=True),
    # 2b-repair-4 F2: earlier writers' rows are converted once (registry/migrate.py); nothing reads them unconverted
    Mutant("F2-opens-over-unconverted-rows", "a cache (and so a gateway) opens a database still holding an unconverted row", CACHE,
           "            if left:\n", "            if False:\n",
           (PV + "RestrictionsSurviveReload.test_no_gateway_opens_a_database_holding_an_unconverted_row",),
           (PV + "RestrictionsSurviveReload.test_a_prohibition_survives_a_fresh_process_reload",), db=True),
    Mutant("F2-serves-unconverted-row", "a row an older gateway writes after the cache opened is served", CACHE,
           "WHERE identity = %s AND restriction_inputs \"", "WHERE identity = %s \"",
           (PV + "RestrictionsSurviveReload.test_a_row_an_older_gateway_writes_later_is_never_served",),
           (PV + "RestrictionsSurviveReload.test_a_prohibition_survives_a_fresh_process_reload",), db=True),
    Mutant("F2-harvest-rows-unmarked", "the harvest's new row is not marked current", "research_gateway/harvest/index.py",
           "now(), true) ", "now(), false) ",
           (PV + "RestrictionsSurviveReload.test_the_harvests_rows_are_current_and_read_from_record_sources",),
           ("tests.test_harvest.IndexRoundTrip.test_a_metadata_licence_never_becomes_the_content_licence",), db=True),
    Mutant("F2-marked-unconverted", "the migration marks a row without converting it", MIGRATE,
           "(json.dumps(converted(canonical, stored), default=str), identity)", "(json.dumps(canonical, default=str), identity)",
           (PV + "RestrictionsSurviveReload.test_a_pre_repair_rows_prohibition_survives_the_migration",
            PV + "RestrictionsSurviveReload.test_the_live_gateways_rows_keep_their_leads_statements"),
           (PV + "RestrictionsSurviveReload.test_control_a_legacy_permitted_row_reloads_permitted",), db=True),
    Mutant("F2-legacy-members-unread", "a row with no members of its own is converted without its record_sources rows", MIGRATE,
           '                stored = [] if canonical.get("provenance") else stored_members(cur, identity)\n', "                stored = []\n",
           (PV + "RestrictionsSurviveReload.test_a_legacy_rows_lead_statement_survives_the_migration",),
           (PV + "RestrictionsSurviveReload.test_a_legacy_row_keeps_its_stored_prohibition",), db=True),
    Mutant("F2-lead-statements-dropped", "the lead's own statements, among the record's fields, are not its member's", MIGRATE,
           "    members[at] = {**lead, **members[at]}\n", "",
           (PV + "RestrictionsSurviveReload.test_the_live_gateways_rows_keep_their_leads_statements",
            PV + "RestrictionsSurviveReload.test_a_legacy_rows_lead_statement_survives_the_migration"),
           (PV + "RestrictionsSurviveReload.test_control_a_pre_repair_unrestricted_row_reloads_permitted",), db=True),
    Mutant("F2-lead-statements-spread", "a lead with no member of its own puts its statements on the first member", MIGRATE,
           'm.get("source_id") == canonical.get("source_id")), None)', 'm.get("source_id") == canonical.get("source_id")), 0)',
           (PV + "RestrictionsSurviveReload.test_a_legacy_rows_lead_statement_survives_the_migration",),
           (PV + "RestrictionsSurviveReload.test_the_live_gateways_rows_keep_their_leads_statements",), db=True),
    Mutant("F2-prohibition-not-converted", "task 2b's stored prohibition is not converted into its member's statement", MIGRATE,
           '    derived = {"redistributable": False} if facts.get("redistribution") == "prohibited" else {}\n', "    derived = {}\n",
           (PV + "RestrictionsSurviveReload.test_a_pre_repair_rows_prohibition_survives_the_migration",),
           (PV + "RestrictionsSurviveReload.test_control_a_pre_repair_unrestricted_row_reloads_permitted",), db=True),
    Mutant("F2-personal-use-not-converted", "task 2b's stored personal use is dropped by the migration", MIGRATE,
           '        if facts.get("access") == "personal_use" and m.get("third_party_restricted") is not True:\n', "        if False:\n",
           (PV + "RestrictionsSurviveReload.test_a_pre_repair_rows_personal_use_survives_the_migration_as_inferred",),
           (PV + "RestrictionsSurviveReload.test_control_a_pre_repair_unrestricted_row_reloads_permitted",), db=True),
    Mutant("F2-inferred-as-stated", "a personal use inferred from legacy data is recorded as the source's third-party terms", MIGRATE,
           '            derived["inferred_personal_use"] = True\n', '            derived["third_party_restricted"] = True\n',
           (PV + "RestrictionsSurviveReload.test_a_pre_repair_rows_personal_use_survives_the_migration_as_inferred",
            PV + "RestrictionsSurviveReload.test_a_pre_repair_rows_prohibition_survives_the_migration"),
           (PV + "RestrictionsSurviveReload.test_the_migration_runs_once_and_says_when_it_is_done",), db=True),
    Mutant("F2-stated-also-inferred", "a personal use its kept third-party statement explains is also recorded as inferred", MIGRATE,
           ' and m.get("third_party_restricted") is not True:\n', ":\n",
           (PV + "RestrictionsSurviveReload.test_a_pre_repair_rows_personal_use_survives_the_migration_as_inferred",),
           (PV + "RestrictionsSurviveReload.test_control_a_pre_repair_unrestricted_row_reloads_permitted",), db=True),
    Mutant("F2-inferred-not-kept", "a stored member summary forgets its inferred restriction", "research_gateway/core/canonical.py",
           "MEMBER_RESTRICTIONS + INFERRED_RESTRICTIONS if", "MEMBER_RESTRICTIONS if",
           (PV + "RestrictionsSurviveReload.test_a_pre_repair_rows_personal_use_survives_the_migration_as_inferred",),
           (PV + "RestrictionsSurviveReload.test_a_prohibition_survives_a_fresh_process_reload",), db=True),
    Mutant("F2-inferred-ignored", "an inferred personal use does not restrict access", LIC,
           ' and not member.get("inferred_personal_use")\n', "\n",
           (PV + "RestrictionsSurviveReload.test_a_pre_repair_rows_personal_use_survives_the_migration_as_inferred",),
           (PV + "PermissionFacts.test_each_fact_follows_its_own_rule",), db=True),
    Mutant("L-metadata-licence-as-content", "a harvest loader's metadata licence stands in for the content licence",
           "research_gateway/harvest/index.py", '    content_license = record.get("license")\n',
           '    content_license = metadata_license or record.get("license")\n',
           ("tests.test_harvest.IndexRoundTrip.test_a_metadata_licence_never_becomes_the_content_licence",
            "tests.test_harvest.IndexRoundTrip.test_the_real_loaders_pass_their_licence_as_metadata"),
           ("tests.test_harvest.IndexRoundTrip.test_control_a_content_licence_decides_with_or_without_a_metadata_licence",), db=True),
    Mutant("L-availability-by-kind", "a file or full-text record is content by its kind, links only or not", LIC,
           '    return {"availability": "content" if has_content else "metadata",',
           '    return {"availability": "content" if has_content or kind in ("full_text", "file") else "metadata",',
           (PV + "ReturnedRecords.test_a_link_only_listing_is_metadata_not_content", PV + "PermissionFacts.test_each_fact_follows_its_own_rule"),
           (PV + "ReturnedRecords.test_a_download_carries_its_own_facts",)),
    Mutant("L-loader-subset", "the DB loader drops licence and freshness", APP,
           '                  "auth", "secret_ref", "key_instructions", "license", "use_commercial", "use_evidence", "freshness_lag",',
           '                  "auth", "secret_ref", "key_instructions", "use_commercial", "use_evidence",',
           (PV + "DatabaseBackedSources.test_the_loader_returns_every_registry_field_of_every_source",
            PV + "DatabaseBackedSources.test_a_db_backed_gateway_answers_with_licence_and_freshness"),
           (PV + "DatabaseBackedSources.test_control_the_database_is_what_is_read",), db=True),
    Mutant("L-conditional-permitted", "a conditional licence permits redistribution", LIC,
           '    return "permitted" if KNOWN.get(cid) else "conditional"', '    return "permitted"',
           (PV + "PermissionFacts.test_each_fact_follows_its_own_rule",), (PV + "PermissionFacts.test_unknown_is_never_permitted",)),
    Mutant("L-unknown-permitted", "an unidentified licence permits redistribution", LIC,
           '    if cid is None:\n        return "unknown"', '    if cid is None:\n        return "permitted"',
           (PV + "PermissionFacts.test_unknown_is_never_permitted", PV + "PermissionFacts.test_each_fact_follows_its_own_rule"),
           (PV + "PermissionFacts.test_a_merged_record_takes_the_most_restrictive_of_its_members",)),
    Mutant("L-storage-is-redistribution", "redistribution is read off the storage verdict (the old one flag)", LIC,
           '            "redistribution": content_redistribution(member.get("license"), member.get("redistributable"))}',
           '            "redistribution": "permitted" if storable(source, record) else "prohibited"}',
           (PV + "PermissionFacts.test_each_fact_follows_its_own_rule", PV + "PermissionFacts.test_no_fact_is_a_function_of_another"),
           (PV + "PermissionFacts.test_unknown_is_never_permitted",)),
    Mutant("L-adapter-prohibition-ignored", "a source's no-redistribution statement is ignored", LIC,
           "    if adapter_flag is False:\n        return \"prohibited\"", "    if False:\n        return \"prohibited\"",
           (PV + "PermissionFacts.test_each_fact_follows_its_own_rule",), (PV + "PermissionFacts.test_unknown_is_never_permitted",)),
    Mutant("L-merge-least-restrictive", "a merged record takes its least restricted member", LIC,
           "    return {fact: min((p[fact] for p in per_member), key=values.index) for fact, values in order.items()}",
           "    return {fact: max((p[fact] for p in per_member), key=values.index) for fact, values in order.items()}",
           (PV + "PermissionFacts.test_a_merged_record_takes_the_most_restrictive_of_its_members",
            PV + "ReturnedRecords.test_a_merged_find_record_carries_each_members_provenance_and_facts"),
           (PV + "PermissionFacts.test_each_fact_follows_its_own_rule",)),
    Mutant("L-stored-drops-facts", "a stored job result loses the four facts", "research_gateway/core/canonical.py",
           '        out["permissions"] = {k: perms[k] for k in PERMISSION_FACTS}', "        pass",
           (PV + "ReturnedRecords.test_a_merged_find_record_carries_each_members_provenance_and_facts",),
           (PV + "ReturnedRecords.test_a_resolved_record_and_its_cached_copy_carry_the_facts",)),
    Mutant("L-persisted-redistributable", "every persisted row is written redistributable (the old meaning)", "research_gateway/core/cache.py",
           '                     redistribution == "permitted", redistribution, prov.get("metadata_license")),',
           '                     True, redistribution, prov.get("metadata_license")),',
           ("tests.test_cache_dedup.PersistentCache.test_only_storable_members_reach_the_database_and_storage_is_not_redistribution",),
           ("tests.test_cache_dedup.PersistentCache.test_reload_keeps_member_stamps_links_and_attribution_verbatim",), db=True),
]
